// Generated by Sterling SDK Generator
// Orchestrator Control Plane API v0.1.0

import type { VersSdkClient } from "../client";
import type { EnvVarsResponse, CreateRepositoryResponse, PublicRepositoryInfo, WhoamiOrg, ListTagsResponse, CreateRepoTagRequest, OrchestratorVersion, WhoamiApiKey, CommitVmRequest, ListCommitsResponse, DeployResponse, ListRepoTagsResponse, BaseImageInfo, VmExecResponse, CreateBaseImageResponse, VmExecRequest, NewVmsResponse, VmExecStreamAttachRequest, VmUpdateStateRequest, DeleteBaseImageResponse, ListPublicRepositoriesResponse, CreateTagRequest, ListRepositoriesResponse, CreateRepoTagResponse, CommitInfo, DeleteDomainResponse, RepositoryInfo, ValidateKeyResponse, VmSshKeyResponse, VmState, VmReadFileResponse, SetEnvVarsRequest, VmCommitResponse, ForkRepositoryResponse, ImageSourceRequest, VmUpdateStateEnum, ErrorResponse, UpdateCommitRequest, CreateRepositoryRequest, DomainResponse, DeploySettings, CreateBaseImageRequest, ForkRepositoryRequest, VmCommitEntity, TagInfo, VmWriteFileRequest, VmExecLogStream, VmExecLogEntry, LabelVmRequest, VmMetadataResponse, WhoamiResponse, SetRepositoryVisibilityRequest, UpdateRepoTagRequest, VmCreateVmConfig, NewVmResponse, FromCommitVmRequest, VM, CreateDomainRequest, UpdateTagRequest, UploadBaseImageResponse, WhoamiUser, BaseImageStatusResponse, ListBaseImagesResponse, NewRootRequest, VmResizeDiskRequest, VmDeleteResponse, CreateTagResponse, DeployRequest, RepoTagInfo, VmExecLogResponse, VmLogsParams, UpdateVmStateParams, ReadFileVmParams, ResizeVmDiskParams, CreateNewRootVmParams, BranchByRefParams, BranchByTagParams, BranchVmParams, DeleteVmParams, BranchByVmParams, CommitVmParams, ListDomainsParams, BranchByCommitParams,  } from "../models";
import type { RequestOptions } from "../request-options";

export class CommitTagsResource {
  private _client: VersSdkClient;

  constructor(client: VersSdkClient) {
    this._client = client;
  }

  /**
   * 
   */
  async listTags(options?: RequestOptions): Promise<ListTagsResponse> {
    return this._client.listTags(options);
  }

  /**
   * 
   */
  async createTag(body: CreateTagRequest, options?: RequestOptions): Promise<CreateTagResponse> {
    return this._client.createTag(body, options);
  }

  /**
   * 
   */
  async getTag(tag_name: string, options?: RequestOptions): Promise<TagInfo> {
    return this._client.getTag(tag_name, options);
  }

  /**
   * 
   */
  async deleteTag(tag_name: string, options?: RequestOptions): Promise<any> {
    return this._client.deleteTag(tag_name, options);
  }

  /**
   * 
   */
  async updateTag(tag_name: string, body: UpdateTagRequest, options?: RequestOptions): Promise<any> {
    return this._client.updateTag(tag_name, body, options);
  }

}
