// Generated by Sterling SDK Generator
// Orchestrator Control Plane API v0.1.0

import type { VersSdkClient } from "../client";
import type { EnvVarsResponse, CreateRepositoryResponse, PublicRepositoryInfo, ListTagsResponse, CreateRepoTagRequest, OrchestratorVersion, ListCommitsResponse, DeployResponse, ListRepoTagsResponse, BaseImageInfo, VmExecResponse, CreateBaseImageResponse, VmExecRequest, NewVmsResponse, VmExecStreamAttachRequest, VmUpdateStateRequest, DeleteBaseImageResponse, ListPublicRepositoriesResponse, CreateTagRequest, ListRepositoriesResponse, CreateRepoTagResponse, CommitInfo, DeleteDomainResponse, RepositoryInfo, ValidateKeyResponse, VmSshKeyResponse, VmState, VmReadFileResponse, SetEnvVarsRequest, VmCommitResponse, ForkRepositoryResponse, ImageSourceRequest, VmUpdateStateEnum, ErrorResponse, UpdateCommitRequest, CreateRepositoryRequest, DomainResponse, VmCommitRequest, DeploySettings, CreateBaseImageRequest, ForkRepositoryRequest, VmCommitEntity, TagInfo, VmWriteFileRequest, VmExecLogStream, VmExecLogEntry, LabelVmRequest, VmMetadataResponse, SetRepositoryVisibilityRequest, UpdateRepoTagRequest, VmCreateVmConfig, NewVmResponse, FromCommitVmRequest, VM, CreateDomainRequest, UpdateTagRequest, UploadBaseImageResponse, BaseImageStatusResponse, ListBaseImagesResponse, NewRootRequest, VmResizeDiskRequest, VmDeleteResponse, CreateTagResponse, DeployRequest, RepoTagInfo, VmExecLogResponse, ResizeVmDiskParams, CreateNewRootVmParams, VmLogsParams, BranchByRefParams, BranchByTagParams, BranchVmParams, UpdateVmStateParams, DeleteVmParams, BranchByVmParams, CommitVmParams, ListDomainsParams, ReadFileVmParams, BranchByCommitParams,  } from "../models";
import type { RequestOptions } from "../request-options";

export class DomainsResource {
  private _client: VersSdkClient;

  constructor(client: VersSdkClient) {
    this._client = client;
  }

  /**
   * 
   */
  async getDomain(domain_id: string, options?: RequestOptions): Promise<DomainResponse> {
    return this._client.getDomain(domain_id, options);
  }

  /**
   * 
   */
  async deleteDomain(domain_id: string, options?: RequestOptions): Promise<DeleteDomainResponse> {
    return this._client.deleteDomain(domain_id, options);
  }

  /**
   * 
   */
  async listDomains(params?: ListDomainsParams, options?: RequestOptions): Promise<DomainResponse[]> {
    return this._client.listDomains(params, options);
  }

  /**
   * 
   */
  async createDomain(body: CreateDomainRequest, options?: RequestOptions): Promise<DomainResponse> {
    return this._client.createDomain(body, options);
  }

}
