// Generated by Sterling SDK Generator
// Orchestrator Control Plane API v0.1.0

import type { VersSdkClient } from "../client";
import type { EnvVarsResponse, CreateRepositoryResponse, PublicRepositoryInfo, WhoamiOrg, ListTagsResponse, CreateRepoTagRequest, OrchestratorVersion, WhoamiApiKey, CommitVmRequest, ListCommitsResponse, DeployResponse, ListRepoTagsResponse, BaseImageInfo, VmExecResponse, CreateBaseImageResponse, VmExecRequest, NewVmsResponse, VmExecStreamAttachRequest, VmUpdateStateRequest, DeleteBaseImageResponse, ListPublicRepositoriesResponse, CreateTagRequest, ListRepositoriesResponse, CreateRepoTagResponse, CommitInfo, DeleteDomainResponse, RepositoryInfo, ValidateKeyResponse, VmSshKeyResponse, VmState, VmReadFileResponse, SetEnvVarsRequest, VmCommitResponse, ForkRepositoryResponse, ImageSourceRequest, VmUpdateStateEnum, ErrorResponse, UpdateCommitRequest, CreateRepositoryRequest, DomainResponse, DeploySettings, CreateBaseImageRequest, ForkRepositoryRequest, VmCommitEntity, TagInfo, VmWriteFileRequest, VmExecLogStream, VmExecLogEntry, LabelVmRequest, VmMetadataResponse, WhoamiResponse, SetRepositoryVisibilityRequest, UpdateRepoTagRequest, VmCreateVmConfig, NewVmResponse, FromCommitVmRequest, VM, CreateDomainRequest, UpdateTagRequest, UploadBaseImageResponse, WhoamiUser, BaseImageStatusResponse, ListBaseImagesResponse, NewRootRequest, VmResizeDiskRequest, VmDeleteResponse, CreateTagResponse, DeployRequest, RepoTagInfo, VmExecLogResponse, VmLogsParams, UpdateVmStateParams, ReadFileVmParams, ResizeVmDiskParams, CreateNewRootVmParams, BranchByRefParams, BranchByTagParams, BranchVmParams, DeleteVmParams, BranchByVmParams, CommitVmParams, ListDomainsParams, BranchByCommitParams,  } from "../models";
import type { RequestOptions } from "../request-options";

export class EnvVarsResource {
  private _client: VersSdkClient;

  constructor(client: VersSdkClient) {
    this._client = client;
  }

  /**
   * 
   */
  async listEnvVars(options?: RequestOptions): Promise<EnvVarsResponse> {
    return this._client.listEnvVars(options);
  }

  /**
   * 
   */
  async setEnvVars(body: SetEnvVarsRequest, options?: RequestOptions): Promise<EnvVarsResponse> {
    return this._client.setEnvVars(body, options);
  }

  /**
   * 
   */
  async deleteEnvVar(key: string, options?: RequestOptions): Promise<any> {
    return this._client.deleteEnvVar(key, options);
  }

}
