// Generated by Sterling SDK Generator
// Orchestrator Control Plane API v0.1.0

import type { VersSdkClient } from "../client";
import type { EnvVarsResponse, CreateRepositoryResponse, PublicRepositoryInfo, WhoamiOrg, ListTagsResponse, CreateRepoTagRequest, OrchestratorVersion, WhoamiApiKey, CommitVmRequest, ListCommitsResponse, DeployResponse, ListRepoTagsResponse, BaseImageInfo, VmExecResponse, CreateBaseImageResponse, VmExecRequest, NewVmsResponse, VmExecStreamAttachRequest, VmUpdateStateRequest, DeleteBaseImageResponse, ListPublicRepositoriesResponse, CreateTagRequest, ListRepositoriesResponse, CreateRepoTagResponse, CommitInfo, DeleteDomainResponse, RepositoryInfo, ValidateKeyResponse, VmSshKeyResponse, VmState, VmReadFileResponse, SetEnvVarsRequest, VmCommitResponse, ForkRepositoryResponse, ImageSourceRequest, VmUpdateStateEnum, ErrorResponse, UpdateCommitRequest, CreateRepositoryRequest, DomainResponse, DeploySettings, CreateBaseImageRequest, ForkRepositoryRequest, VmCommitEntity, TagInfo, VmWriteFileRequest, VmExecLogStream, VmExecLogEntry, LabelVmRequest, VmMetadataResponse, WhoamiResponse, SetRepositoryVisibilityRequest, UpdateRepoTagRequest, VmCreateVmConfig, NewVmResponse, FromCommitVmRequest, VM, CreateDomainRequest, UpdateTagRequest, UploadBaseImageResponse, WhoamiUser, BaseImageStatusResponse, ListBaseImagesResponse, NewRootRequest, VmResizeDiskRequest, VmDeleteResponse, CreateTagResponse, DeployRequest, RepoTagInfo, VmExecLogResponse, VmLogsParams, UpdateVmStateParams, ReadFileVmParams, ResizeVmDiskParams, CreateNewRootVmParams, BranchByRefParams, BranchByTagParams, BranchVmParams, DeleteVmParams, BranchByVmParams, CommitVmParams, ListDomainsParams, BranchByCommitParams,  } from "../models";
import type { RequestOptions } from "../request-options";

export class PublicRepositoriesResource {
  private _client: VersSdkClient;

  constructor(client: VersSdkClient) {
    this._client = client;
  }

  /**
   * 
   */
  async listPublicRepoTags(org_name: string, repo_name: string, options?: RequestOptions): Promise<ListRepoTagsResponse> {
    return this._client.listPublicRepoTags(org_name, repo_name, options);
  }

  /**
   * 
   */
  async getPublicRepoTag(org_name: string, repo_name: string, tag_name: string, options?: RequestOptions): Promise<RepoTagInfo> {
    return this._client.getPublicRepoTag(org_name, repo_name, tag_name, options);
  }

  /**
   * 
   */
  async getPublicRepository(org_name: string, repo_name: string, options?: RequestOptions): Promise<PublicRepositoryInfo> {
    return this._client.getPublicRepository(org_name, repo_name, options);
  }

  /**
   * 
   */
  async listPublicRepositories(options?: RequestOptions): Promise<ListPublicRepositoriesResponse> {
    return this._client.listPublicRepositories(options);
  }

}
