// Generated by Sterling SDK Generator
// Orchestrator Control Plane API v0.1.0

import type { VersSdkClient } from "../client";
import type { EnvVarsResponse, CreateRepositoryResponse, PublicRepositoryInfo, ListTagsResponse, CreateRepoTagRequest, OrchestratorVersion, ListCommitsResponse, DeployResponse, ListRepoTagsResponse, BaseImageInfo, VmExecResponse, CreateBaseImageResponse, VmExecRequest, NewVmsResponse, VmExecStreamAttachRequest, VmUpdateStateRequest, DeleteBaseImageResponse, ListPublicRepositoriesResponse, CreateTagRequest, ListRepositoriesResponse, CreateRepoTagResponse, CommitInfo, DeleteDomainResponse, RepositoryInfo, ValidateKeyResponse, VmSshKeyResponse, VmState, VmReadFileResponse, SetEnvVarsRequest, VmCommitResponse, ForkRepositoryResponse, ImageSourceRequest, VmUpdateStateEnum, ErrorResponse, UpdateCommitRequest, CreateRepositoryRequest, DomainResponse, VmCommitRequest, DeploySettings, CreateBaseImageRequest, ForkRepositoryRequest, VmCommitEntity, TagInfo, VmWriteFileRequest, VmExecLogStream, VmExecLogEntry, LabelVmRequest, VmMetadataResponse, SetRepositoryVisibilityRequest, UpdateRepoTagRequest, VmCreateVmConfig, NewVmResponse, FromCommitVmRequest, VM, CreateDomainRequest, UpdateTagRequest, UploadBaseImageResponse, BaseImageStatusResponse, ListBaseImagesResponse, NewRootRequest, VmResizeDiskRequest, VmDeleteResponse, CreateTagResponse, DeployRequest, RepoTagInfo, VmExecLogResponse, ResizeVmDiskParams, CreateNewRootVmParams, VmLogsParams, BranchByRefParams, BranchByTagParams, BranchVmParams, UpdateVmStateParams, DeleteVmParams, BranchByVmParams, CommitVmParams, ListDomainsParams, ReadFileVmParams, BranchByCommitParams,  } from "../models";
import type { RequestOptions } from "../request-options";

export class RepositoriesResource {
  private _client: VersSdkClient;

  constructor(client: VersSdkClient) {
    this._client = client;
  }

  /**
   * 
   */
  async getRepoTag(repo_name: string, tag_name: string, options?: RequestOptions): Promise<RepoTagInfo> {
    return this._client.getRepoTag(repo_name, tag_name, options);
  }

  /**
   * 
   */
  async deleteRepoTag(repo_name: string, tag_name: string, options?: RequestOptions): Promise<any> {
    return this._client.deleteRepoTag(repo_name, tag_name, options);
  }

  /**
   * 
   */
  async updateRepoTag(repo_name: string, tag_name: string, body: UpdateRepoTagRequest, options?: RequestOptions): Promise<any> {
    return this._client.updateRepoTag(repo_name, tag_name, body, options);
  }

  /**
   * 
   */
  async getRepository(repo_name: string, options?: RequestOptions): Promise<RepositoryInfo> {
    return this._client.getRepository(repo_name, options);
  }

  /**
   * 
   */
  async deleteRepository(repo_name: string, options?: RequestOptions): Promise<any> {
    return this._client.deleteRepository(repo_name, options);
  }

  /**
   * 
   */
  async forkRepository(body: ForkRepositoryRequest, options?: RequestOptions): Promise<ForkRepositoryResponse> {
    return this._client.forkRepository(body, options);
  }

  /**
   * 
   */
  async listRepositories(options?: RequestOptions): Promise<ListRepositoriesResponse> {
    return this._client.listRepositories(options);
  }

  /**
   * 
   */
  async createRepository(body: CreateRepositoryRequest, options?: RequestOptions): Promise<CreateRepositoryResponse> {
    return this._client.createRepository(body, options);
  }

  /**
   * 
   */
  async listRepoTags(repo_name: string, options?: RequestOptions): Promise<ListRepoTagsResponse> {
    return this._client.listRepoTags(repo_name, options);
  }

  /**
   * 
   */
  async createRepoTag(repo_name: string, body: CreateRepoTagRequest, options?: RequestOptions): Promise<CreateRepoTagResponse> {
    return this._client.createRepoTag(repo_name, body, options);
  }

  /**
   * 
   */
  async setRepositoryVisibility(repo_name: string, body: SetRepositoryVisibilityRequest, options?: RequestOptions): Promise<any> {
    return this._client.setRepositoryVisibility(repo_name, body, options);
  }

}
