// Generated by Sterling SDK Generator
// Orchestrator Control Plane API v0.1.0

import type { VersSdkClient } from "../client";
import type { EnvVarsResponse, CreateRepositoryResponse, PublicRepositoryInfo, ListTagsResponse, CreateRepoTagRequest, OrchestratorVersion, ListCommitsResponse, DeployResponse, ListRepoTagsResponse, BaseImageInfo, VmExecResponse, CreateBaseImageResponse, VmExecRequest, NewVmsResponse, VmExecStreamAttachRequest, VmUpdateStateRequest, DeleteBaseImageResponse, ListPublicRepositoriesResponse, CreateTagRequest, ListRepositoriesResponse, CreateRepoTagResponse, CommitInfo, DeleteDomainResponse, RepositoryInfo, ValidateKeyResponse, VmSshKeyResponse, VmState, VmReadFileResponse, SetEnvVarsRequest, VmCommitResponse, ForkRepositoryResponse, ImageSourceRequest, VmUpdateStateEnum, ErrorResponse, UpdateCommitRequest, CreateRepositoryRequest, DomainResponse, VmCommitRequest, DeploySettings, CreateBaseImageRequest, ForkRepositoryRequest, VmCommitEntity, TagInfo, VmWriteFileRequest, VmExecLogStream, VmExecLogEntry, LabelVmRequest, VmMetadataResponse, SetRepositoryVisibilityRequest, UpdateRepoTagRequest, VmCreateVmConfig, NewVmResponse, FromCommitVmRequest, VM, CreateDomainRequest, UpdateTagRequest, UploadBaseImageResponse, BaseImageStatusResponse, ListBaseImagesResponse, NewRootRequest, VmResizeDiskRequest, VmDeleteResponse, CreateTagResponse, DeployRequest, RepoTagInfo, VmExecLogResponse, ResizeVmDiskParams, CreateNewRootVmParams, VmLogsParams, BranchByRefParams, BranchByTagParams, BranchVmParams, UpdateVmStateParams, DeleteVmParams, BranchByVmParams, CommitVmParams, ListDomainsParams, ReadFileVmParams, BranchByCommitParams,  } from "../models";
import type { RequestOptions } from "../request-options";

export class VmResource {
  private _client: VersSdkClient;

  constructor(client: VersSdkClient) {
    this._client = client;
  }

  /**
   * 
   */
  async vmStatus(vm_id: string, options?: RequestOptions): Promise<VM> {
    return this._client.vmStatus(vm_id, options);
  }

  /**
   * 
   */
  async resizeVmDisk(vm_id: string, body: VmResizeDiskRequest, params?: ResizeVmDiskParams, options?: RequestOptions): Promise<any> {
    return this._client.resizeVmDisk(vm_id, body, params, options);
  }

  /**
   * 
   */
  async execVmStreamAttach(vm_id: string, body: VmExecStreamAttachRequest, options?: RequestOptions): Promise<any> {
    return this._client.execVmStreamAttach(vm_id, body, options);
  }

  /**
   * 
   */
  async listVms(options?: RequestOptions): Promise<VM[]> {
    return this._client.listVms(options);
  }

  /**
   * 
   */
  async createNewRootVm(body: NewRootRequest, params?: CreateNewRootVmParams, options?: RequestOptions): Promise<NewVmResponse> {
    return this._client.createNewRootVm(body, params, options);
  }

  /**
   * 
   */
  async vmLogs(vm_id: string, params?: VmLogsParams, options?: RequestOptions): Promise<VmExecLogResponse> {
    return this._client.vmLogs(vm_id, params, options);
  }

  /**
   * 
   */
  async branchByRef(repo_name: string, tag_name: string, body: Record<string, unknown>, params?: BranchByRefParams, options?: RequestOptions): Promise<NewVmsResponse> {
    return this._client.branchByRef(repo_name, tag_name, body, params, options);
  }

  /**
   * 
   */
  async labelVm(vm_id: string, body: LabelVmRequest, options?: RequestOptions): Promise<any> {
    return this._client.labelVm(vm_id, body, options);
  }

  /**
   * 
   */
  async branchByTag(tag_name: string, body: Record<string, unknown>, params?: BranchByTagParams, options?: RequestOptions): Promise<NewVmsResponse> {
    return this._client.branchByTag(tag_name, body, params, options);
  }

  /**
   * 
   */
  async branchVm(vm_or_commit_id: string, body: Record<string, unknown>, params?: BranchVmParams, options?: RequestOptions): Promise<NewVmsResponse> {
    return this._client.branchVm(vm_or_commit_id, body, params, options);
  }

  /**
   * 
   */
  async listParentCommits(commit_id: string, options?: RequestOptions): Promise<VmCommitEntity[]> {
    return this._client.listParentCommits(commit_id, options);
  }

  /**
   * 
   */
  async updateVmState(vm_id: string, body: VmUpdateStateRequest, params?: UpdateVmStateParams, options?: RequestOptions): Promise<any> {
    return this._client.updateVmState(vm_id, body, params, options);
  }

  /**
   * 
   */
  async restoreFromCommit(body: FromCommitVmRequest, options?: RequestOptions): Promise<NewVmResponse> {
    return this._client.restoreFromCommit(body, options);
  }

  /**
   * 
   */
  async getVmMetadata(vm_id: string, options?: RequestOptions): Promise<VmMetadataResponse> {
    return this._client.getVmMetadata(vm_id, options);
  }

  /**
   * 
   */
  async deleteVm(vm_id: string, params?: DeleteVmParams, options?: RequestOptions): Promise<VmDeleteResponse> {
    return this._client.deleteVm(vm_id, params, options);
  }

  /**
   * 
   */
  async branchByVm(vm_id: string, body: Record<string, unknown>, params?: BranchByVmParams, options?: RequestOptions): Promise<NewVmsResponse> {
    return this._client.branchByVm(vm_id, body, params, options);
  }

  /**
   * 
   */
  async commitVm(vm_id: string, body: VmCommitRequest, params?: CommitVmParams, options?: RequestOptions): Promise<VmCommitResponse> {
    return this._client.commitVm(vm_id, body, params, options);
  }

  /**
   * 
   */
  async execVm(vm_id: string, body: VmExecRequest, options?: RequestOptions): Promise<VmExecResponse> {
    return this._client.execVm(vm_id, body, options);
  }

  /**
   * 
   */
  async execVmStream(vm_id: string, body: VmExecRequest, options?: RequestOptions): Promise<any> {
    return this._client.execVmStream(vm_id, body, options);
  }

  /**
   * 
   */
  async sshKey(vm_id: string, options?: RequestOptions): Promise<VmSshKeyResponse> {
    return this._client.sshKey(vm_id, options);
  }

  /**
   * 
   */
  async readFileVm(vm_id: string, params?: ReadFileVmParams, options?: RequestOptions): Promise<VmReadFileResponse> {
    return this._client.readFileVm(vm_id, params, options);
  }

  /**
   * 
   */
  async writeFileVm(vm_id: string, body: VmWriteFileRequest, options?: RequestOptions): Promise<any> {
    return this._client.writeFileVm(vm_id, body, options);
  }

  /**
   * 
   */
  async branchByCommit(commit_id: string, body: Record<string, unknown>, params?: BranchByCommitParams, options?: RequestOptions): Promise<NewVmsResponse> {
    return this._client.branchByCommit(commit_id, body, params, options);
  }

}
