// Generated by Sterling SDK Generator
// VM SSH convenience wrapper

import { SSHClient } from './ssh';
import type { SSHOptions, SSHConnectionInfo } from './ssh';
import type { VersSdkClient } from '../client';

/**
 * Connect to a VM via SSH-over-TLS.
 *
 * Fetches the SSH key and connection info from the API, then returns
 * an SSHClient ready to execute commands, open shells, or transfer files.
 *
 * @param client - An authenticated API client instance
 * @param vmId - The VM identifier to connect to
 * @param hostname - The hostname to connect to (e.g. from client base URL)
 * @param options - Optional SSH connection settings
 * @returns A connected SSHClient
 */
export async function connectVmSSH(
  client: VersSdkClient,
  vmId: string,
  hostname: string,
  options: SSHOptions = {},
): Promise<SSHClient> {
  const keyInfo = await client.sshKey(vmId);

  const connectionInfo: SSHConnectionInfo = {
    vmId,
    privateKey: keyInfo.ssh_private_key,
    hostname,
    port: keyInfo.ssh_port,
  };

  return new SSHClient(connectionInfo, options);
}
