// Generated by Sterling SDK Generator — test suite
// Orchestrator Control Plane API v0.1.0

import { VersSdkClient } from "../src/client";
import { APIError, NotFoundError, BadRequestError, InternalServerError } from "../src/errors";

// ── Fetch mock ──────────────────────────────────────────────────────────

interface CapturedRequest {
  url: string;
  method: string;
  body: string | null;
}

let captured: CapturedRequest | null = null;
let mockStatus = 200;
let mockBody: unknown = {};
const origFetch = globalThis.fetch;

(globalThis as any).fetch = async (_input: string | URL | Request, init?: RequestInit): Promise<Response> => {
  const url = typeof _input === "string" ? _input : _input instanceof URL ? _input.toString() : (_input as Request).url;
  captured = {
    url,
    method: (init?.method ?? "GET").toUpperCase(),
    body: init?.body ? String(init.body) : null,
  };
  return new Response(JSON.stringify(mockBody), {
    status: mockStatus,
    headers: { "content-type": "application/json" },
  });
};

function reset(status = 200, body: unknown = {}): void {
  captured = null;
  mockStatus = status;
  mockBody = body;
}

function ok(cond: boolean, msg: string): void {
  if (!cond) throw new Error(msg);
}

function makeClient(): VersSdkClient {
  return new VersSdkClient({ baseUrl: "http://localhost:9999", apiKey: "test-key", maxRetries: 0 });
}

// ── Operation tests ─────────────────────────────────────────────────────

async function test_vm_status(): Promise<void> {
  reset();
  const c = makeClient();
  await c.vmStatus("test-id");
  ok(captured !== null, "vm_status: request captured");
  ok(captured!.method === "GET", "vm_status: expected GET, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "vm_status: url prefix");
}

async function test_resize_vm_disk(): Promise<void> {
  reset();
  const c = makeClient();
  await c.resizeVmDisk("test-id", {} as any);
  ok(captured !== null, "resize_vm_disk: request captured");
  ok(captured!.method === "PATCH", "resize_vm_disk: expected PATCH, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "resize_vm_disk: url prefix");
  ok(captured!.body !== null, "resize_vm_disk: body sent");
}

async function test_exec_vm_stream_attach(): Promise<void> {
  reset();
  const c = makeClient();
  await c.execVmStreamAttach("test-id", {} as any);
  ok(captured !== null, "exec_vm_stream_attach: request captured");
  ok(captured!.method === "POST", "exec_vm_stream_attach: expected POST, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "exec_vm_stream_attach: url prefix");
  ok(captured!.body !== null, "exec_vm_stream_attach: body sent");
}

async function test_list_vms(): Promise<void> {
  reset();
  const c = makeClient();
  await c.listVms();
  ok(captured !== null, "list_vms: request captured");
  ok(captured!.method === "GET", "list_vms: expected GET, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "list_vms: url prefix");
}

async function test_create_new_root_vm(): Promise<void> {
  reset();
  const c = makeClient();
  await c.createNewRootVm({} as any);
  ok(captured !== null, "create_new_root_vm: request captured");
  ok(captured!.method === "POST", "create_new_root_vm: expected POST, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "create_new_root_vm: url prefix");
  ok(captured!.body !== null, "create_new_root_vm: body sent");
}

async function test_vm_logs(): Promise<void> {
  reset();
  const c = makeClient();
  await c.vmLogs("test-id");
  ok(captured !== null, "vm_logs: request captured");
  ok(captured!.method === "GET", "vm_logs: expected GET, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "vm_logs: url prefix");
}

async function test_branch_by_ref(): Promise<void> {
  reset();
  const c = makeClient();
  await c.branchByRef("test-id", "test-id", {} as any);
  ok(captured !== null, "branch_by_ref: request captured");
  ok(captured!.method === "POST", "branch_by_ref: expected POST, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "branch_by_ref: url prefix");
  ok(captured!.body !== null, "branch_by_ref: body sent");
}

async function test_label_vm(): Promise<void> {
  reset();
  const c = makeClient();
  await c.labelVm("test-id", {} as any);
  ok(captured !== null, "label_vm: request captured");
  ok(captured!.method === "PATCH", "label_vm: expected PATCH, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "label_vm: url prefix");
  ok(captured!.body !== null, "label_vm: body sent");
}

async function test_list_public_commits(): Promise<void> {
  reset();
  const c = makeClient();
  await c.listPublicCommits();
  ok(captured !== null, "list_public_commits: request captured");
  ok(captured!.method === "GET", "list_public_commits: expected GET, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "list_public_commits: url prefix");
}

async function test_get_image_status(): Promise<void> {
  reset();
  const c = makeClient();
  await c.getImageStatus("test-id");
  ok(captured !== null, "get_image_status: request captured");
  ok(captured!.method === "GET", "get_image_status: expected GET, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "get_image_status: url prefix");
}

async function test_list_public_repo_tags(): Promise<void> {
  reset();
  const c = makeClient();
  await c.listPublicRepoTags("test-id", "test-id");
  ok(captured !== null, "list_public_repo_tags: request captured");
  ok(captured!.method === "GET", "list_public_repo_tags: expected GET, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "list_public_repo_tags: url prefix");
}

async function test_version_handler(): Promise<void> {
  reset();
  const c = makeClient();
  await c.versionHandler();
  ok(captured !== null, "version_handler: request captured");
  ok(captured!.method === "GET", "version_handler: expected GET, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "version_handler: url prefix");
}

async function test_branch_by_tag(): Promise<void> {
  reset();
  const c = makeClient();
  await c.branchByTag("test-id", {} as any);
  ok(captured !== null, "branch_by_tag: request captured");
  ok(captured!.method === "POST", "branch_by_tag: expected POST, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "branch_by_tag: url prefix");
  ok(captured!.body !== null, "branch_by_tag: body sent");
}

async function test_get_repo_tag(): Promise<void> {
  reset();
  const c = makeClient();
  await c.getRepoTag("test-id", "test-id");
  ok(captured !== null, "get_repo_tag: request captured");
  ok(captured!.method === "GET", "get_repo_tag: expected GET, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "get_repo_tag: url prefix");
}

async function test_delete_repo_tag(): Promise<void> {
  reset();
  const c = makeClient();
  await c.deleteRepoTag("test-id", "test-id");
  ok(captured !== null, "delete_repo_tag: request captured");
  ok(captured!.method === "DELETE", "delete_repo_tag: expected DELETE, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "delete_repo_tag: url prefix");
}

async function test_update_repo_tag(): Promise<void> {
  reset();
  const c = makeClient();
  await c.updateRepoTag("test-id", "test-id", {} as any);
  ok(captured !== null, "update_repo_tag: request captured");
  ok(captured!.method === "PATCH", "update_repo_tag: expected PATCH, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "update_repo_tag: url prefix");
  ok(captured!.body !== null, "update_repo_tag: body sent");
}

async function test_branch_vm(): Promise<void> {
  reset();
  const c = makeClient();
  await c.branchVm("test-id", {} as any);
  ok(captured !== null, "branch_vm: request captured");
  ok(captured!.method === "POST", "branch_vm: expected POST, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "branch_vm: url prefix");
  ok(captured!.body !== null, "branch_vm: body sent");
}

async function test_get_repository(): Promise<void> {
  reset();
  const c = makeClient();
  await c.getRepository("test-id");
  ok(captured !== null, "get_repository: request captured");
  ok(captured!.method === "GET", "get_repository: expected GET, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "get_repository: url prefix");
}

async function test_delete_repository(): Promise<void> {
  reset();
  const c = makeClient();
  await c.deleteRepository("test-id");
  ok(captured !== null, "delete_repository: request captured");
  ok(captured!.method === "DELETE", "delete_repository: expected DELETE, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "delete_repository: url prefix");
}

async function test_list_parent_commits(): Promise<void> {
  reset();
  const c = makeClient();
  await c.listParentCommits("test-id");
  ok(captured !== null, "list_parent_commits: request captured");
  ok(captured!.method === "GET", "list_parent_commits: expected GET, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "list_parent_commits: url prefix");
}

async function test_validate_key(): Promise<void> {
  reset();
  const c = makeClient();
  await c.validateKey({} as any);
  ok(captured !== null, "validate_key: request captured");
  ok(captured!.method === "POST", "validate_key: expected POST, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "validate_key: url prefix");
  ok(captured!.body !== null, "validate_key: body sent");
}

async function test_fork_repository(): Promise<void> {
  reset();
  const c = makeClient();
  await c.forkRepository({} as any);
  ok(captured !== null, "fork_repository: request captured");
  ok(captured!.method === "POST", "fork_repository: expected POST, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "fork_repository: url prefix");
  ok(captured!.body !== null, "fork_repository: body sent");
}

async function test_list_repositories(): Promise<void> {
  reset();
  const c = makeClient();
  await c.listRepositories();
  ok(captured !== null, "list_repositories: request captured");
  ok(captured!.method === "GET", "list_repositories: expected GET, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "list_repositories: url prefix");
}

async function test_create_repository(): Promise<void> {
  reset();
  const c = makeClient();
  await c.createRepository({} as any);
  ok(captured !== null, "create_repository: request captured");
  ok(captured!.method === "POST", "create_repository: expected POST, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "create_repository: url prefix");
  ok(captured!.body !== null, "create_repository: body sent");
}

async function test_update_vm_state(): Promise<void> {
  reset();
  const c = makeClient();
  await c.updateVmState("test-id", {} as any);
  ok(captured !== null, "update_vm_state: request captured");
  ok(captured!.method === "PATCH", "update_vm_state: expected PATCH, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "update_vm_state: url prefix");
  ok(captured!.body !== null, "update_vm_state: body sent");
}

async function test_create_image(): Promise<void> {
  reset();
  const c = makeClient();
  await c.createImage({} as any);
  ok(captured !== null, "create_image: request captured");
  ok(captured!.method === "POST", "create_image: expected POST, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "create_image: url prefix");
  ok(captured!.body !== null, "create_image: body sent");
}

async function test_restore_from_commit(): Promise<void> {
  reset();
  const c = makeClient();
  await c.restoreFromCommit({} as any);
  ok(captured !== null, "restore_from_commit: request captured");
  ok(captured!.method === "POST", "restore_from_commit: expected POST, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "restore_from_commit: url prefix");
  ok(captured!.body !== null, "restore_from_commit: body sent");
}

async function test_get_domain(): Promise<void> {
  reset();
  const c = makeClient();
  await c.getDomain("test-id");
  ok(captured !== null, "get_domain: request captured");
  ok(captured!.method === "GET", "get_domain: expected GET, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "get_domain: url prefix");
}

async function test_delete_domain(): Promise<void> {
  reset();
  const c = makeClient();
  await c.deleteDomain("test-id");
  ok(captured !== null, "delete_domain: request captured");
  ok(captured!.method === "DELETE", "delete_domain: expected DELETE, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "delete_domain: url prefix");
}

async function test_list_tags(): Promise<void> {
  reset();
  const c = makeClient();
  await c.listTags();
  ok(captured !== null, "list_tags: request captured");
  ok(captured!.method === "GET", "list_tags: expected GET, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "list_tags: url prefix");
}

async function test_create_tag(): Promise<void> {
  reset();
  const c = makeClient();
  await c.createTag({} as any);
  ok(captured !== null, "create_tag: request captured");
  ok(captured!.method === "POST", "create_tag: expected POST, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "create_tag: url prefix");
  ok(captured!.body !== null, "create_tag: body sent");
}

async function test_list_public_repositories(): Promise<void> {
  reset();
  const c = makeClient();
  await c.listPublicRepositories();
  ok(captured !== null, "list_public_repositories: request captured");
  ok(captured!.method === "GET", "list_public_repositories: expected GET, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "list_public_repositories: url prefix");
}

async function test_get_public_repo_tag(): Promise<void> {
  reset();
  const c = makeClient();
  await c.getPublicRepoTag("test-id", "test-id", "test-id");
  ok(captured !== null, "get_public_repo_tag: request captured");
  ok(captured!.method === "GET", "get_public_repo_tag: expected GET, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "get_public_repo_tag: url prefix");
}

async function test_get_vm_metadata(): Promise<void> {
  reset();
  const c = makeClient();
  await c.getVmMetadata("test-id");
  ok(captured !== null, "get_vm_metadata: request captured");
  ok(captured!.method === "GET", "get_vm_metadata: expected GET, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "get_vm_metadata: url prefix");
}

async function test_list_env_vars(): Promise<void> {
  reset();
  const c = makeClient();
  await c.listEnvVars();
  ok(captured !== null, "list_env_vars: request captured");
  ok(captured!.method === "GET", "list_env_vars: expected GET, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "list_env_vars: url prefix");
}

async function test_set_env_vars(): Promise<void> {
  reset();
  const c = makeClient();
  await c.setEnvVars({} as any);
  ok(captured !== null, "set_env_vars: request captured");
  ok(captured!.method === "PUT", "set_env_vars: expected PUT, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "set_env_vars: url prefix");
  ok(captured!.body !== null, "set_env_vars: body sent");
}

async function test_delete_vm(): Promise<void> {
  reset();
  const c = makeClient();
  await c.deleteVm("test-id");
  ok(captured !== null, "delete_vm: request captured");
  ok(captured!.method === "DELETE", "delete_vm: expected DELETE, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "delete_vm: url prefix");
}

async function test_list_commits(): Promise<void> {
  reset();
  const c = makeClient();
  await c.listCommits();
  ok(captured !== null, "list_commits: request captured");
  ok(captured!.method === "GET", "list_commits: expected GET, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "list_commits: url prefix");
}

async function test_get_tag(): Promise<void> {
  reset();
  const c = makeClient();
  await c.getTag("test-id");
  ok(captured !== null, "get_tag: request captured");
  ok(captured!.method === "GET", "get_tag: expected GET, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "get_tag: url prefix");
}

async function test_delete_tag(): Promise<void> {
  reset();
  const c = makeClient();
  await c.deleteTag("test-id");
  ok(captured !== null, "delete_tag: request captured");
  ok(captured!.method === "DELETE", "delete_tag: expected DELETE, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "delete_tag: url prefix");
}

async function test_update_tag(): Promise<void> {
  reset();
  const c = makeClient();
  await c.updateTag("test-id", {} as any);
  ok(captured !== null, "update_tag: request captured");
  ok(captured!.method === "PATCH", "update_tag: expected PATCH, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "update_tag: url prefix");
  ok(captured!.body !== null, "update_tag: body sent");
}

async function test_branch_by_vm(): Promise<void> {
  reset();
  const c = makeClient();
  await c.branchByVm("test-id", {} as any);
  ok(captured !== null, "branch_by_vm: request captured");
  ok(captured!.method === "POST", "branch_by_vm: expected POST, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "branch_by_vm: url prefix");
  ok(captured!.body !== null, "branch_by_vm: body sent");
}

async function test_delete_env_var(): Promise<void> {
  reset();
  const c = makeClient();
  await c.deleteEnvVar("test-id");
  ok(captured !== null, "delete_env_var: request captured");
  ok(captured!.method === "DELETE", "delete_env_var: expected DELETE, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "delete_env_var: url prefix");
}

async function test_delete_image(): Promise<void> {
  reset();
  const c = makeClient();
  await c.deleteImage("test-id");
  ok(captured !== null, "delete_image: request captured");
  ok(captured!.method === "DELETE", "delete_image: expected DELETE, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "delete_image: url prefix");
}

async function test_commit_vm(): Promise<void> {
  reset();
  const c = makeClient();
  await c.commitVm("test-id", {} as any);
  ok(captured !== null, "commit_vm: request captured");
  ok(captured!.method === "POST", "commit_vm: expected POST, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "commit_vm: url prefix");
  ok(captured!.body !== null, "commit_vm: body sent");
}

async function test_delete_commit(): Promise<void> {
  reset();
  const c = makeClient();
  await c.deleteCommit("test-id");
  ok(captured !== null, "delete_commit: request captured");
  ok(captured!.method === "DELETE", "delete_commit: expected DELETE, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "delete_commit: url prefix");
}

async function test_update_commit(): Promise<void> {
  reset();
  const c = makeClient();
  await c.updateCommit("test-id", {} as any);
  ok(captured !== null, "update_commit: request captured");
  ok(captured!.method === "PATCH", "update_commit: expected PATCH, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "update_commit: url prefix");
  ok(captured!.body !== null, "update_commit: body sent");
}

async function test_list_repo_tags(): Promise<void> {
  reset();
  const c = makeClient();
  await c.listRepoTags("test-id");
  ok(captured !== null, "list_repo_tags: request captured");
  ok(captured!.method === "GET", "list_repo_tags: expected GET, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "list_repo_tags: url prefix");
}

async function test_create_repo_tag(): Promise<void> {
  reset();
  const c = makeClient();
  await c.createRepoTag("test-id", {} as any);
  ok(captured !== null, "create_repo_tag: request captured");
  ok(captured!.method === "POST", "create_repo_tag: expected POST, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "create_repo_tag: url prefix");
  ok(captured!.body !== null, "create_repo_tag: body sent");
}

async function test_deploy_handler(): Promise<void> {
  reset();
  const c = makeClient();
  await c.deployHandler({} as any);
  ok(captured !== null, "deploy_handler: request captured");
  ok(captured!.method === "POST", "deploy_handler: expected POST, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "deploy_handler: url prefix");
  ok(captured!.body !== null, "deploy_handler: body sent");
}

async function test_exec_vm(): Promise<void> {
  reset();
  const c = makeClient();
  await c.execVm("test-id", {} as any);
  ok(captured !== null, "exec_vm: request captured");
  ok(captured!.method === "POST", "exec_vm: expected POST, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "exec_vm: url prefix");
  ok(captured!.body !== null, "exec_vm: body sent");
}

async function test_set_repository_visibility(): Promise<void> {
  reset();
  const c = makeClient();
  await c.setRepositoryVisibility("test-id", {} as any);
  ok(captured !== null, "set_repository_visibility: request captured");
  ok(captured!.method === "PATCH", "set_repository_visibility: expected PATCH, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "set_repository_visibility: url prefix");
  ok(captured!.body !== null, "set_repository_visibility: body sent");
}

async function test_exec_vm_stream(): Promise<void> {
  reset();
  const c = makeClient();
  await c.execVmStream("test-id", {} as any);
  ok(captured !== null, "exec_vm_stream: request captured");
  ok(captured!.method === "POST", "exec_vm_stream: expected POST, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "exec_vm_stream: url prefix");
  ok(captured!.body !== null, "exec_vm_stream: body sent");
}

async function test_list_domains(): Promise<void> {
  reset();
  const c = makeClient();
  await c.listDomains();
  ok(captured !== null, "list_domains: request captured");
  ok(captured!.method === "GET", "list_domains: expected GET, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "list_domains: url prefix");
}

async function test_create_domain(): Promise<void> {
  reset();
  const c = makeClient();
  await c.createDomain({} as any);
  ok(captured !== null, "create_domain: request captured");
  ok(captured!.method === "POST", "create_domain: expected POST, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "create_domain: url prefix");
  ok(captured!.body !== null, "create_domain: body sent");
}

async function test_ssh_key(): Promise<void> {
  reset();
  const c = makeClient();
  await c.sshKey("test-id");
  ok(captured !== null, "ssh_key: request captured");
  ok(captured!.method === "GET", "ssh_key: expected GET, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "ssh_key: url prefix");
}

async function test_list_images(): Promise<void> {
  reset();
  const c = makeClient();
  await c.listImages();
  ok(captured !== null, "list_images: request captured");
  ok(captured!.method === "GET", "list_images: expected GET, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "list_images: url prefix");
}

async function test_read_file_vm(): Promise<void> {
  reset();
  const c = makeClient();
  await c.readFileVm("test-id");
  ok(captured !== null, "read_file_vm: request captured");
  ok(captured!.method === "GET", "read_file_vm: expected GET, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "read_file_vm: url prefix");
}

async function test_write_file_vm(): Promise<void> {
  reset();
  const c = makeClient();
  await c.writeFileVm("test-id", {} as any);
  ok(captured !== null, "write_file_vm: request captured");
  ok(captured!.method === "PUT", "write_file_vm: expected PUT, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "write_file_vm: url prefix");
  ok(captured!.body !== null, "write_file_vm: body sent");
}

async function test_upload_image(): Promise<void> {
  reset();
  const c = makeClient();
  await c.uploadImage({} as any);
  ok(captured !== null, "upload_image: request captured");
  ok(captured!.method === "POST", "upload_image: expected POST, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "upload_image: url prefix");
  ok(captured!.body !== null, "upload_image: body sent");
}

async function test_get_public_repository(): Promise<void> {
  reset();
  const c = makeClient();
  await c.getPublicRepository("test-id", "test-id");
  ok(captured !== null, "get_public_repository: request captured");
  ok(captured!.method === "GET", "get_public_repository: expected GET, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "get_public_repository: url prefix");
}

async function test_branch_by_commit(): Promise<void> {
  reset();
  const c = makeClient();
  await c.branchByCommit("test-id", {} as any);
  ok(captured !== null, "branch_by_commit: request captured");
  ok(captured!.method === "POST", "branch_by_commit: expected POST, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "branch_by_commit: url prefix");
  ok(captured!.body !== null, "branch_by_commit: body sent");
}

// ── Error handling tests ────────────────────────────────────────────────

async function testErrors(): Promise<void> {
  const c = makeClient();

  reset(400, { message: "bad request" });
  try { await c.vmStatus("test-id"); ok(false, "should throw"); } catch (e: unknown) {
    ok(e instanceof BadRequestError, "400 → BadRequestError");
  }

  reset(404, { message: "not found" });
  try { await c.vmStatus("test-id"); ok(false, "should throw"); } catch (e: unknown) {
    ok(e instanceof NotFoundError, "404 → NotFoundError");
  }

  reset(500, { message: "server error" });
  try { await c.vmStatus("test-id"); ok(false, "should throw"); } catch (e: unknown) {
    ok(e instanceof InternalServerError, "500 → InternalServerError");
  }
}

// ── Runner ──────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  let passed = 0;
  let failed = 0;

  const tests: Array<[string, () => Promise<void>]> = [
    ["vm_status", test_vm_status],
    ["resize_vm_disk", test_resize_vm_disk],
    ["exec_vm_stream_attach", test_exec_vm_stream_attach],
    ["list_vms", test_list_vms],
    ["create_new_root_vm", test_create_new_root_vm],
    ["vm_logs", test_vm_logs],
    ["branch_by_ref", test_branch_by_ref],
    ["label_vm", test_label_vm],
    ["list_public_commits", test_list_public_commits],
    ["get_image_status", test_get_image_status],
    ["list_public_repo_tags", test_list_public_repo_tags],
    ["version_handler", test_version_handler],
    ["branch_by_tag", test_branch_by_tag],
    ["get_repo_tag", test_get_repo_tag],
    ["delete_repo_tag", test_delete_repo_tag],
    ["update_repo_tag", test_update_repo_tag],
    ["branch_vm", test_branch_vm],
    ["get_repository", test_get_repository],
    ["delete_repository", test_delete_repository],
    ["list_parent_commits", test_list_parent_commits],
    ["validate_key", test_validate_key],
    ["fork_repository", test_fork_repository],
    ["list_repositories", test_list_repositories],
    ["create_repository", test_create_repository],
    ["update_vm_state", test_update_vm_state],
    ["create_image", test_create_image],
    ["restore_from_commit", test_restore_from_commit],
    ["get_domain", test_get_domain],
    ["delete_domain", test_delete_domain],
    ["list_tags", test_list_tags],
    ["create_tag", test_create_tag],
    ["list_public_repositories", test_list_public_repositories],
    ["get_public_repo_tag", test_get_public_repo_tag],
    ["get_vm_metadata", test_get_vm_metadata],
    ["list_env_vars", test_list_env_vars],
    ["set_env_vars", test_set_env_vars],
    ["delete_vm", test_delete_vm],
    ["list_commits", test_list_commits],
    ["get_tag", test_get_tag],
    ["delete_tag", test_delete_tag],
    ["update_tag", test_update_tag],
    ["branch_by_vm", test_branch_by_vm],
    ["delete_env_var", test_delete_env_var],
    ["delete_image", test_delete_image],
    ["commit_vm", test_commit_vm],
    ["delete_commit", test_delete_commit],
    ["update_commit", test_update_commit],
    ["list_repo_tags", test_list_repo_tags],
    ["create_repo_tag", test_create_repo_tag],
    ["deploy_handler", test_deploy_handler],
    ["exec_vm", test_exec_vm],
    ["set_repository_visibility", test_set_repository_visibility],
    ["exec_vm_stream", test_exec_vm_stream],
    ["list_domains", test_list_domains],
    ["create_domain", test_create_domain],
    ["ssh_key", test_ssh_key],
    ["list_images", test_list_images],
    ["read_file_vm", test_read_file_vm],
    ["write_file_vm", test_write_file_vm],
    ["upload_image", test_upload_image],
    ["get_public_repository", test_get_public_repository],
    ["branch_by_commit", test_branch_by_commit],
    ["error_handling", testErrors],
  ];

  for (const [name, fn] of tests) {
    try {
      await fn();
      passed++;
      console.log(`  ✓ ${name}`);
    } catch (e) {
      failed++;
      console.error(`  ✗ ${name}: ${(e as Error).message}`);
    }
  }

  globalThis.fetch = origFetch;
  console.log(`\n${passed} passed, ${failed} failed`);
  if (failed > 0) process.exit(1);
}

main();
