// Generated by Sterling SDK Generator
// Orchestrator Control Plane API v0.1.0

import type { EnvVarsResponse, CreateRepositoryResponse, PublicRepositoryInfo, ListTagsResponse, CreateRepoTagRequest, OrchestratorVersion, ListCommitsResponse, DeployResponse, ListRepoTagsResponse, BaseImageInfo, VmExecResponse, CreateBaseImageResponse, VmExecRequest, NewVmsResponse, VmExecStreamAttachRequest, VmUpdateStateRequest, DeleteBaseImageResponse, ListPublicRepositoriesResponse, CreateTagRequest, ListRepositoriesResponse, CreateRepoTagResponse, CommitInfo, DeleteDomainResponse, RepositoryInfo, ValidateKeyResponse, VmSshKeyResponse, VmState, VmReadFileResponse, SetEnvVarsRequest, VmCommitResponse, ForkRepositoryResponse, ImageSourceRequest, VmUpdateStateEnum, ErrorResponse, UpdateCommitRequest, CreateRepositoryRequest, DomainResponse, VmCommitRequest, DeploySettings, CreateBaseImageRequest, ForkRepositoryRequest, VmCommitEntity, TagInfo, VmWriteFileRequest, VmExecLogStream, VmExecLogEntry, LabelVmRequest, VmMetadataResponse, SetRepositoryVisibilityRequest, UpdateRepoTagRequest, VmCreateVmConfig, NewVmResponse, FromCommitVmRequest, VM, CreateDomainRequest, UpdateTagRequest, UploadBaseImageResponse, BaseImageStatusResponse, ListBaseImagesResponse, NewRootRequest, VmResizeDiskRequest, VmDeleteResponse, CreateTagResponse, DeployRequest, RepoTagInfo, VmExecLogResponse, ResizeVmDiskParams, CreateNewRootVmParams, VmLogsParams, BranchByRefParams, BranchByTagParams, BranchVmParams, UpdateVmStateParams, DeleteVmParams, BranchByVmParams, CommitVmParams, ListDomainsParams, ReadFileVmParams, BranchByCommitParams,  } from "./models";
import type { RequestOptions } from "./request-options";
import { APIError, APIConnectionError } from "./errors";
import { getEnv, detectRuntime, getDefaultFetch } from "./shims";
import { VmResource } from "./resources/vm";
import { RepositoriesResource } from "./resources/repositories";
import { CommitsResource } from "./resources/commits";
import { CommitTagsResource } from "./resources/commit-tags";
import { DomainsResource } from "./resources/domains";
import { EnvVarsResource } from "./resources/env-vars";
import { PublicRepositoriesResource } from "./resources/public-repositories";

export interface Logger {
  error(message: string, ...args: unknown[]): void;
  warn(message: string, ...args: unknown[]): void;
  info(message: string, ...args: unknown[]): void;
  debug(message: string, ...args: unknown[]): void;
}

export type LogLevel = 'debug' | 'info' | 'warn' | 'error' | 'off';

const LOG_LEVEL_ORDER: Record<LogLevel, number> = {
  off: 0,
  error: 1,
  warn: 2,
  info: 3,
  debug: 4,
};

function parseLogLevel(value: string | undefined): LogLevel | undefined {
  if (value && value in LOG_LEVEL_ORDER) return value as LogLevel;
  return undefined;
}

export interface VersSdkClientOptions {
  baseUrl?: string;
  apiKey?: string;
  headers?: Record<string, string | null>;
  /** Maximum number of retries on 5xx/network errors. Default: 2 */
  maxRetries?: number;
  /** Request timeout in milliseconds. Default: 30000 */
  timeout?: number;
  /** Log level. Defaults to VERS_LOG env var or 'warn'. */
  logLevel?: LogLevel;
  /** Custom fetch implementation for testing, proxying, or custom transport. */
  fetch?: typeof fetch;
  /** Additional options to pass to every underlying `fetch` call (e.g. dispatcher, keepalive). */
  fetchOptions?: RequestInit;
  /** Custom logger (compatible with pino, winston, bunyan, consola, etc.). Default: console */
  logger?: Logger;
}

// Status codes that are retryable even though they are 4xx
const RETRYABLE_STATUS_CODES = new Set([408, 409, 429]);

function isRetryableStatus(status: number): boolean {
  return status >= 500 || RETRYABLE_STATUS_CODES.has(status);
}

function retryDelay(retryCount: number): number {
  const base = 500 * Math.pow(2, retryCount);
  const jitter = Math.random() * base * 0.25;
  return base + jitter;
}

function parseRetryAfter(headerValue: string | null): number | null {
  if (headerValue == null) return null;
  const seconds = Number(headerValue);
  if (!Number.isNaN(seconds)) {
    return Math.min(Math.max(seconds * 1000, 0), 60000);
  }
  const date = new Date(headerValue);
  if (!Number.isNaN(date.getTime())) {
    const delayMs = date.getTime() - Date.now();
    return Math.min(Math.max(delayMs, 0), 60000);
  }
  return null;
}

export class VersSdkClient {
  private baseUrl: string;
  private apiKey?: string;
  private headers: Record<string, string | null>;
  private maxRetries: number;
  private timeout: number;
  private logLevel: LogLevel;
  private fetchFn: typeof fetch;
  private fetchOptions: RequestInit;
  private logger: Logger;

  // Resource accessors
  readonly vm: VmResource;
  readonly repositories: RepositoriesResource;
  readonly commits: CommitsResource;
  readonly commitTags: CommitTagsResource;
  readonly domains: DomainsResource;
  readonly envVars: EnvVarsResource;
  readonly publicRepositories: PublicRepositoriesResource;

  constructor(options: VersSdkClientOptions = {}) {
    this.baseUrl = options.baseUrl ?? getEnv("VERS_BASE_URL") ?? "https://api.vers.sh";
    this.apiKey = options.apiKey ?? getEnv("VERS_API_KEY");
    this.headers = options.headers ?? {};
    this.maxRetries = options.maxRetries ?? 2;
    this.timeout = options.timeout ?? 30000;
    this.logLevel = options.logLevel ?? parseLogLevel(getEnv("VERS_LOG")) ?? 'warn';
    this.fetchFn = options.fetch ?? globalThis.fetch;
    this.fetchOptions = options.fetchOptions ?? {};
    this.logger = options.logger ?? console;

    // Initialize resources
    this.vm = new VmResource(this);
    this.repositories = new RepositoriesResource(this);
    this.commits = new CommitsResource(this);
    this.commitTags = new CommitTagsResource(this);
    this.domains = new DomainsResource(this);
    this.envVars = new EnvVarsResource(this);
    this.publicRepositories = new PublicRepositoriesResource(this);
  }

  /**
   * Make a GET request to an arbitrary path. Uses the same authentication,
   * retries, and error handling as generated methods.
   */
  get<T = unknown>(path: string, options?: RequestOptions): Promise<T> {
    return this.request("GET", path, undefined, options).then(r => r.json() as Promise<T>);
  }

  /**
   * Make a POST request to an arbitrary path.
   */
  post<T = unknown>(path: string, body?: unknown, options?: RequestOptions): Promise<T> {
    return this.request("POST", path, body, options).then(r => r.json() as Promise<T>);
  }

  /**
   * Make a PUT request to an arbitrary path.
   */
  put<T = unknown>(path: string, body?: unknown, options?: RequestOptions): Promise<T> {
    return this.request("PUT", path, body, options).then(r => r.json() as Promise<T>);
  }

  /**
   * Make a PATCH request to an arbitrary path.
   */
  patch<T = unknown>(path: string, body?: unknown, options?: RequestOptions): Promise<T> {
    return this.request("PATCH", path, body, options).then(r => r.json() as Promise<T>);
  }

  /**
   * Make a DELETE request to an arbitrary path.
   */
  del<T = unknown>(path: string, options?: RequestOptions): Promise<T> {
    return this.request("DELETE", path, undefined, options).then(r => r.json() as Promise<T>);
  }

  private log(level: LogLevel, message: string): void {
    if (level === 'off' || LOG_LEVEL_ORDER[level] > LOG_LEVEL_ORDER[this.logLevel]) return;
    const ts = new Date().toISOString();
    const tag = `[vers_sdk]`;
    const msg = `${ts} ${tag} ${message}`;
    this.logger[level](msg);
  }

  private mergeHeaders(...sources: (Record<string, string | null | undefined> | undefined)[]): Record<string, string> {
    const merged: Record<string, string> = {};
    for (const source of sources) {
      if (!source) continue;
      for (const [key, value] of Object.entries(source)) {
        if (value === null || value === undefined) {
          // Remove header (case-insensitive)
          for (const k of Object.keys(merged)) {
            if (k.toLowerCase() === key.toLowerCase()) delete merged[k];
          }
        } else {
          merged[key] = value;
        }
      }
    }
    return merged;
  }

  private get userAgent(): string {
    const runtime = detectRuntime();
    let rt: string;
    switch (runtime) {
      case "deno":
        rt = `deno/${(globalThis as any).Deno?.version?.deno ?? "unknown"}`;
        break;
      case "bun":
        rt = `bun/${(globalThis as any).Bun?.version ?? "unknown"}`;
        break;
      case "node":
        rt = `node/${process.versions?.node ?? "unknown"}`;
        break;
      case "edge":
        rt = "edge-runtime";
        break;
      case "browser":
        rt = "browser";
        break;
      default:
        rt = "unknown-runtime";
    }
    const os = typeof process !== "undefined"
      ? `${process.platform ?? "unknown"}/${process.arch ?? "unknown"}`
      : "unknown-os";
    return `vers-sdk/0.1.8 ${rt} ${os}`;
  }

  private async request(method: string, path: string, body?: unknown, options?: RequestOptions): Promise<Response> {
    const defaultHeaders: Record<string, string> = {
      "Content-Type": "application/json",
      "User-Agent": this.userAgent,
    };
    if (this.apiKey) {
      defaultHeaders["Authorization"] = `Bearer ${this.apiKey}`;
    }
    const headers = this.mergeHeaders(defaultHeaders, this.headers, options?.headers);

    const mutating = ["POST", "PUT", "PATCH", "DELETE"].includes(method.toUpperCase());
    if (mutating) {
      headers["X-Idempotency-Key"] = crypto.randomUUID();
    }
    // Merge per-request headers; null values remove the header
    if (options?.headers) {
      for (const [key, value] of Object.entries(options.headers)) {
        if (value === null) {
          delete headers[key];
        } else {
          headers[key] = value;
        }
      }
    }

    const effectiveTimeout = options?.timeout ?? this.timeout;

    this.log('debug', `request: ${method} ${path}`);
    let lastError: unknown;
    let lastRetryAfterUsed = false;
    for (let attempt = 0; attempt <= this.maxRetries; attempt++) {
      if (attempt > 0 && !lastRetryAfterUsed) {
        this.log('info', `retry attempt ${attempt}/${this.maxRetries} for ${method} ${path}`);
        await new Promise((resolve) => setTimeout(resolve, retryDelay(attempt - 1)));
      }
      lastRetryAfterUsed = false;

      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), effectiveTimeout);
      // If caller provided an AbortSignal, forward its abort to our controller
      if (options?.signal) {
        if (options.signal.aborted) {
          controller.abort();
        } else {
          options.signal.addEventListener("abort", () => controller.abort(), { once: true });
        }
      }

      try {
        const mergedFetchOptions = { ...this.fetchOptions, ...options?.fetchOptions };
        const response = await this.fetchFn(`${this.baseUrl}${path}`, {
          ...mergedFetchOptions,
          method,
          headers,
          body: body ? JSON.stringify(body) : undefined,
          signal: controller.signal,
        });

        if (isRetryableStatus(response.status) && attempt < this.maxRetries) {
          const retryAfterDelay = parseRetryAfter(response.headers.get('retry-after'));
          if (retryAfterDelay != null) {
            lastRetryAfterUsed = true;
            this.log('info', `retry attempt ${attempt + 1}/${this.maxRetries} for ${method} ${path} (retry-after: ${retryAfterDelay}ms)`);
            await new Promise((resolve) => setTimeout(resolve, retryAfterDelay));
          }
          lastError = new Error(`HTTP ${response.status}`);
          continue;
        }

        this.log('debug', `response: ${response.status} for ${method} ${path}`);

        if (!response.ok) {
          let errorBody: object | undefined;
          let errorMessage: string | undefined;
          try {
            const text = await response.text();
            const ct = response.headers.get("content-type") ?? "";
            if (ct.includes("application/json")) {
              try { errorBody = JSON.parse(text); } catch { errorMessage = text; }
            } else {
              errorMessage = text;
            }
          } catch {}
          const err = APIError.generate(response.status, errorBody, errorMessage, response.headers);
          this.log('error', `API error: ${response.status} ${method} ${path}`);
          throw err;
        }

        return response;
      } catch (error) {
        if (error instanceof APIError) throw error;
        lastError = error;
        this.log('error', `connection error: ${method} ${path} - ${error instanceof Error ? error.message : String(error)}`);
        if (attempt === this.maxRetries) {
          throw new APIConnectionError({ cause: error instanceof Error ? error : undefined });
        }
      } finally {
        clearTimeout(timeoutId);
      }
    }

    throw lastError;
  }

  // ── Flat methods (also accessible via resource accessors) ─────────

  /**
   * 
   */
  async vmStatus(vm_id: string, options?: RequestOptions): Promise<VM> {
    let url = `/api/v1/vm/${vm_id}/status`;
    const resp = await this.request("GET", url, undefined, options);
    const text = await resp.text();
    if (!text) return {} as unknown as VM;
    return JSON.parse(text) as VM;
  }

  /**
   * 
   */
  async resizeVmDisk(vm_id: string, body: VmResizeDiskRequest, params?: ResizeVmDiskParams, options?: RequestOptions): Promise<any> {
    let url = `/api/v1/vm/${vm_id}/disk`;
    const searchParams = new URLSearchParams();
    if (params?.skip_wait_boot !== undefined) searchParams.append("skip_wait_boot", String(params.skip_wait_boot));
    const qs = searchParams.toString();
    if (qs) url += "?" + qs;
    const resp = await this.request("PATCH", url, body, options);
    const text = await resp.text();
    if (!text) return {};
    return JSON.parse(text);
  }

  /**
   * 
   */
  async execVmStreamAttach(vm_id: string, body: VmExecStreamAttachRequest, options?: RequestOptions): Promise<any> {
    let url = `/api/v1/vm/${vm_id}/exec/stream/attach`;
    const resp = await this.request("POST", url, body, options);
    const text = await resp.text();
    if (!text) return {};
    return JSON.parse(text);
  }

  /**
   * 
   */
  async listVms(options?: RequestOptions): Promise<VM[]> {
    let url = "/api/v1/vms";
    const resp = await this.request("GET", url, undefined, options);
    const text = await resp.text();
    if (!text) return [] as unknown as VM[];
    return JSON.parse(text) as VM[];
  }

  /**
   * 
   */
  async createNewRootVm(body: NewRootRequest, params?: CreateNewRootVmParams, options?: RequestOptions): Promise<NewVmResponse> {
    let url = "/api/v1/vm/new_root";
    const searchParams = new URLSearchParams();
    if (params?.wait_boot !== undefined) searchParams.append("wait_boot", String(params.wait_boot));
    const qs = searchParams.toString();
    if (qs) url += "?" + qs;
    const resp = await this.request("POST", url, body, options);
    const text = await resp.text();
    if (!text) return {} as unknown as NewVmResponse;
    return JSON.parse(text) as NewVmResponse;
  }

  /**
   * 
   */
  async vmLogs(vm_id: string, params?: VmLogsParams, options?: RequestOptions): Promise<VmExecLogResponse> {
    let url = `/api/v1/vm/${vm_id}/logs`;
    const searchParams = new URLSearchParams();
    if (params?.offset !== undefined) searchParams.append("offset", String(params.offset));
    if (params?.max_entries !== undefined) searchParams.append("max_entries", String(params.max_entries));
    if (params?.stream !== undefined) searchParams.append("stream", String(params.stream));
    const qs = searchParams.toString();
    if (qs) url += "?" + qs;
    const resp = await this.request("GET", url, undefined, options);
    const text = await resp.text();
    if (!text) return {} as unknown as VmExecLogResponse;
    return JSON.parse(text) as VmExecLogResponse;
  }

  /**
   * 
   */
  async branchByRef(repo_name: string, tag_name: string, body: Record<string, unknown>, params?: BranchByRefParams, options?: RequestOptions): Promise<NewVmsResponse> {
    let url = `/api/v1/vm/branch/by_ref/${repo_name}/${tag_name}`;
    const searchParams = new URLSearchParams();
    if (params?.count !== undefined) searchParams.append("count", String(params.count));
    const qs = searchParams.toString();
    if (qs) url += "?" + qs;
    const resp = await this.request("POST", url, body, options);
    const text = await resp.text();
    if (!text) return {} as unknown as NewVmsResponse;
    return JSON.parse(text) as NewVmsResponse;
  }

  /**
   * 
   */
  async labelVm(vm_id: string, body: LabelVmRequest, options?: RequestOptions): Promise<any> {
    let url = `/api/v1/vm/${vm_id}/label`;
    const resp = await this.request("PATCH", url, body, options);
    const text = await resp.text();
    if (!text) return {};
    return JSON.parse(text);
  }

  /**
   * 
   */
  async listPublicCommits(options?: RequestOptions): Promise<ListCommitsResponse> {
    let url = "/api/v1/commits/public";
    const resp = await this.request("GET", url, undefined, options);
    const text = await resp.text();
    if (!text) return {} as unknown as ListCommitsResponse;
    return JSON.parse(text) as ListCommitsResponse;
  }

  /**
   * 
   */
  async getImageStatus(image_name: string, options?: RequestOptions): Promise<BaseImageStatusResponse> {
    let url = `/api/v1/images/${image_name}/status`;
    const resp = await this.request("GET", url, undefined, options);
    const text = await resp.text();
    if (!text) return {} as unknown as BaseImageStatusResponse;
    return JSON.parse(text) as BaseImageStatusResponse;
  }

  /**
   * 
   */
  async listPublicRepoTags(org_name: string, repo_name: string, options?: RequestOptions): Promise<ListRepoTagsResponse> {
    let url = `/api/v1/public/repositories/${org_name}/${repo_name}/tags`;
    const resp = await this.request("GET", url, undefined, options);
    const text = await resp.text();
    if (!text) return {} as unknown as ListRepoTagsResponse;
    return JSON.parse(text) as ListRepoTagsResponse;
  }

  /**
   * 
   */
  async versionHandler(options?: RequestOptions): Promise<OrchestratorVersion> {
    let url = "/api/v1/system/version";
    const resp = await this.request("GET", url, undefined, options);
    const text = await resp.text();
    if (!text) return {} as unknown as OrchestratorVersion;
    return JSON.parse(text) as OrchestratorVersion;
  }

  /**
   * 
   */
  async branchByTag(tag_name: string, body: Record<string, unknown>, params?: BranchByTagParams, options?: RequestOptions): Promise<NewVmsResponse> {
    let url = `/api/v1/vm/branch/by_tag/${tag_name}`;
    const searchParams = new URLSearchParams();
    if (params?.count !== undefined) searchParams.append("count", String(params.count));
    const qs = searchParams.toString();
    if (qs) url += "?" + qs;
    const resp = await this.request("POST", url, body, options);
    const text = await resp.text();
    if (!text) return {} as unknown as NewVmsResponse;
    return JSON.parse(text) as NewVmsResponse;
  }

  /**
   * 
   */
  async getRepoTag(repo_name: string, tag_name: string, options?: RequestOptions): Promise<RepoTagInfo> {
    let url = `/api/v1/repositories/${repo_name}/tags/${tag_name}`;
    const resp = await this.request("GET", url, undefined, options);
    const text = await resp.text();
    if (!text) return {} as unknown as RepoTagInfo;
    return JSON.parse(text) as RepoTagInfo;
  }

  /**
   * 
   */
  async deleteRepoTag(repo_name: string, tag_name: string, options?: RequestOptions): Promise<any> {
    let url = `/api/v1/repositories/${repo_name}/tags/${tag_name}`;
    const resp = await this.request("DELETE", url, undefined, options);
    const text = await resp.text();
    if (!text) return {};
    return JSON.parse(text);
  }

  /**
   * 
   */
  async updateRepoTag(repo_name: string, tag_name: string, body: UpdateRepoTagRequest, options?: RequestOptions): Promise<any> {
    let url = `/api/v1/repositories/${repo_name}/tags/${tag_name}`;
    const resp = await this.request("PATCH", url, body, options);
    const text = await resp.text();
    if (!text) return {};
    return JSON.parse(text);
  }

  /**
   * 
   */
  async branchVm(vm_or_commit_id: string, body: Record<string, unknown>, params?: BranchVmParams, options?: RequestOptions): Promise<NewVmsResponse> {
    let url = `/api/v1/vm/${vm_or_commit_id}/branch`;
    const searchParams = new URLSearchParams();
    if (params?.keep_paused !== undefined) searchParams.append("keep_paused", String(params.keep_paused));
    if (params?.skip_wait_boot !== undefined) searchParams.append("skip_wait_boot", String(params.skip_wait_boot));
    if (params?.count !== undefined) searchParams.append("count", String(params.count));
    const qs = searchParams.toString();
    if (qs) url += "?" + qs;
    const resp = await this.request("POST", url, body, options);
    const text = await resp.text();
    if (!text) return {} as unknown as NewVmsResponse;
    return JSON.parse(text) as NewVmsResponse;
  }

  /**
   * 
   */
  async getRepository(repo_name: string, options?: RequestOptions): Promise<RepositoryInfo> {
    let url = `/api/v1/repositories/${repo_name}`;
    const resp = await this.request("GET", url, undefined, options);
    const text = await resp.text();
    if (!text) return {} as unknown as RepositoryInfo;
    return JSON.parse(text) as RepositoryInfo;
  }

  /**
   * 
   */
  async deleteRepository(repo_name: string, options?: RequestOptions): Promise<any> {
    let url = `/api/v1/repositories/${repo_name}`;
    const resp = await this.request("DELETE", url, undefined, options);
    const text = await resp.text();
    if (!text) return {};
    return JSON.parse(text);
  }

  /**
   * 
   */
  async listParentCommits(commit_id: string, options?: RequestOptions): Promise<VmCommitEntity[]> {
    let url = `/api/v1/vm/commits/${commit_id}/parents`;
    const resp = await this.request("GET", url, undefined, options);
    const text = await resp.text();
    if (!text) return [] as unknown as VmCommitEntity[];
    return JSON.parse(text) as VmCommitEntity[];
  }

  /**
   * 
   */
  async validateKey(body: Record<string, unknown>, options?: RequestOptions): Promise<ValidateKeyResponse> {
    let url = "/api/v1/keys/validate";
    const resp = await this.request("POST", url, body, options);
    const text = await resp.text();
    if (!text) return {} as unknown as ValidateKeyResponse;
    return JSON.parse(text) as ValidateKeyResponse;
  }

  /**
   * 
   */
  async forkRepository(body: ForkRepositoryRequest, options?: RequestOptions): Promise<ForkRepositoryResponse> {
    let url = "/api/v1/repositories/fork";
    const resp = await this.request("POST", url, body, options);
    const text = await resp.text();
    if (!text) return {} as unknown as ForkRepositoryResponse;
    return JSON.parse(text) as ForkRepositoryResponse;
  }

  /**
   * 
   */
  async listRepositories(options?: RequestOptions): Promise<ListRepositoriesResponse> {
    let url = "/api/v1/repositories";
    const resp = await this.request("GET", url, undefined, options);
    const text = await resp.text();
    if (!text) return {} as unknown as ListRepositoriesResponse;
    return JSON.parse(text) as ListRepositoriesResponse;
  }

  /**
   * 
   */
  async createRepository(body: CreateRepositoryRequest, options?: RequestOptions): Promise<CreateRepositoryResponse> {
    let url = "/api/v1/repositories";
    const resp = await this.request("POST", url, body, options);
    const text = await resp.text();
    if (!text) return {} as unknown as CreateRepositoryResponse;
    return JSON.parse(text) as CreateRepositoryResponse;
  }

  /**
   * 
   */
  async updateVmState(vm_id: string, body: VmUpdateStateRequest, params?: UpdateVmStateParams, options?: RequestOptions): Promise<any> {
    let url = `/api/v1/vm/${vm_id}/state`;
    const searchParams = new URLSearchParams();
    if (params?.skip_wait_boot !== undefined) searchParams.append("skip_wait_boot", String(params.skip_wait_boot));
    const qs = searchParams.toString();
    if (qs) url += "?" + qs;
    const resp = await this.request("PATCH", url, body, options);
    const text = await resp.text();
    if (!text) return {};
    return JSON.parse(text);
  }

  /**
   * 
   */
  async createImage(body: CreateBaseImageRequest, options?: RequestOptions): Promise<CreateBaseImageResponse> {
    let url = "/api/v1/images/create";
    const resp = await this.request("POST", url, body, options);
    const text = await resp.text();
    if (!text) return {} as unknown as CreateBaseImageResponse;
    return JSON.parse(text) as CreateBaseImageResponse;
  }

  /**
   * 
   */
  async restoreFromCommit(body: FromCommitVmRequest, options?: RequestOptions): Promise<NewVmResponse> {
    let url = "/api/v1/vm/from_commit";
    const resp = await this.request("POST", url, body, options);
    const text = await resp.text();
    if (!text) return {} as unknown as NewVmResponse;
    return JSON.parse(text) as NewVmResponse;
  }

  /**
   * 
   */
  async getDomain(domain_id: string, options?: RequestOptions): Promise<DomainResponse> {
    let url = `/api/v1/domains/${domain_id}`;
    const resp = await this.request("GET", url, undefined, options);
    const text = await resp.text();
    if (!text) return {} as unknown as DomainResponse;
    return JSON.parse(text) as DomainResponse;
  }

  /**
   * 
   */
  async deleteDomain(domain_id: string, options?: RequestOptions): Promise<DeleteDomainResponse> {
    let url = `/api/v1/domains/${domain_id}`;
    const resp = await this.request("DELETE", url, undefined, options);
    const text = await resp.text();
    if (!text) return {} as unknown as DeleteDomainResponse;
    return JSON.parse(text) as DeleteDomainResponse;
  }

  /**
   * 
   */
  async listTags(options?: RequestOptions): Promise<ListTagsResponse> {
    let url = "/api/v1/commit_tags";
    const resp = await this.request("GET", url, undefined, options);
    const text = await resp.text();
    if (!text) return {} as unknown as ListTagsResponse;
    return JSON.parse(text) as ListTagsResponse;
  }

  /**
   * 
   */
  async createTag(body: CreateTagRequest, options?: RequestOptions): Promise<CreateTagResponse> {
    let url = "/api/v1/commit_tags";
    const resp = await this.request("POST", url, body, options);
    const text = await resp.text();
    if (!text) return {} as unknown as CreateTagResponse;
    return JSON.parse(text) as CreateTagResponse;
  }

  /**
   * 
   */
  async listPublicRepositories(options?: RequestOptions): Promise<ListPublicRepositoriesResponse> {
    let url = "/api/v1/public/repositories";
    const resp = await this.request("GET", url, undefined, options);
    const text = await resp.text();
    if (!text) return {} as unknown as ListPublicRepositoriesResponse;
    return JSON.parse(text) as ListPublicRepositoriesResponse;
  }

  /**
   * 
   */
  async getPublicRepoTag(org_name: string, repo_name: string, tag_name: string, options?: RequestOptions): Promise<RepoTagInfo> {
    let url = `/api/v1/public/repositories/${org_name}/${repo_name}/tags/${tag_name}`;
    const resp = await this.request("GET", url, undefined, options);
    const text = await resp.text();
    if (!text) return {} as unknown as RepoTagInfo;
    return JSON.parse(text) as RepoTagInfo;
  }

  /**
   * 
   */
  async getVmMetadata(vm_id: string, options?: RequestOptions): Promise<VmMetadataResponse> {
    let url = `/api/v1/vm/${vm_id}/metadata`;
    const resp = await this.request("GET", url, undefined, options);
    const text = await resp.text();
    if (!text) return {} as unknown as VmMetadataResponse;
    return JSON.parse(text) as VmMetadataResponse;
  }

  /**
   * 
   */
  async listEnvVars(options?: RequestOptions): Promise<EnvVarsResponse> {
    let url = "/api/v1/env_vars";
    const resp = await this.request("GET", url, undefined, options);
    const text = await resp.text();
    if (!text) return {} as unknown as EnvVarsResponse;
    return JSON.parse(text) as EnvVarsResponse;
  }

  /**
   * 
   */
  async setEnvVars(body: SetEnvVarsRequest, options?: RequestOptions): Promise<EnvVarsResponse> {
    let url = "/api/v1/env_vars";
    const resp = await this.request("PUT", url, body, options);
    const text = await resp.text();
    if (!text) return {} as unknown as EnvVarsResponse;
    return JSON.parse(text) as EnvVarsResponse;
  }

  /**
   * 
   */
  async deleteVm(vm_id: string, params?: DeleteVmParams, options?: RequestOptions): Promise<VmDeleteResponse> {
    let url = `/api/v1/vm/${vm_id}`;
    const searchParams = new URLSearchParams();
    if (params?.skip_wait_boot !== undefined) searchParams.append("skip_wait_boot", String(params.skip_wait_boot));
    const qs = searchParams.toString();
    if (qs) url += "?" + qs;
    const resp = await this.request("DELETE", url, undefined, options);
    const text = await resp.text();
    if (!text) return {} as unknown as VmDeleteResponse;
    return JSON.parse(text) as VmDeleteResponse;
  }

  /**
   * 
   */
  async listCommits(options?: RequestOptions): Promise<ListCommitsResponse> {
    let url = "/api/v1/commits";
    const resp = await this.request("GET", url, undefined, options);
    const text = await resp.text();
    if (!text) return {} as unknown as ListCommitsResponse;
    return JSON.parse(text) as ListCommitsResponse;
  }

  /**
   * 
   */
  async getTag(tag_name: string, options?: RequestOptions): Promise<TagInfo> {
    let url = `/api/v1/commit_tags/${tag_name}`;
    const resp = await this.request("GET", url, undefined, options);
    const text = await resp.text();
    if (!text) return {} as unknown as TagInfo;
    return JSON.parse(text) as TagInfo;
  }

  /**
   * 
   */
  async deleteTag(tag_name: string, options?: RequestOptions): Promise<any> {
    let url = `/api/v1/commit_tags/${tag_name}`;
    const resp = await this.request("DELETE", url, undefined, options);
    const text = await resp.text();
    if (!text) return {};
    return JSON.parse(text);
  }

  /**
   * 
   */
  async updateTag(tag_name: string, body: UpdateTagRequest, options?: RequestOptions): Promise<any> {
    let url = `/api/v1/commit_tags/${tag_name}`;
    const resp = await this.request("PATCH", url, body, options);
    const text = await resp.text();
    if (!text) return {};
    return JSON.parse(text);
  }

  /**
   * 
   */
  async branchByVm(vm_id: string, body: Record<string, unknown>, params?: BranchByVmParams, options?: RequestOptions): Promise<NewVmsResponse> {
    let url = `/api/v1/vm/branch/by_vm/${vm_id}`;
    const searchParams = new URLSearchParams();
    if (params?.keep_paused !== undefined) searchParams.append("keep_paused", String(params.keep_paused));
    if (params?.skip_wait_boot !== undefined) searchParams.append("skip_wait_boot", String(params.skip_wait_boot));
    if (params?.count !== undefined) searchParams.append("count", String(params.count));
    const qs = searchParams.toString();
    if (qs) url += "?" + qs;
    const resp = await this.request("POST", url, body, options);
    const text = await resp.text();
    if (!text) return {} as unknown as NewVmsResponse;
    return JSON.parse(text) as NewVmsResponse;
  }

  /**
   * 
   */
  async deleteEnvVar(key: string, options?: RequestOptions): Promise<any> {
    let url = `/api/v1/env_vars/${key}`;
    const resp = await this.request("DELETE", url, undefined, options);
    const text = await resp.text();
    if (!text) return {};
    return JSON.parse(text);
  }

  /**
   * 
   */
  async deleteImage(base_image_id: string, options?: RequestOptions): Promise<DeleteBaseImageResponse> {
    let url = `/api/v1/images/images/${base_image_id}`;
    const resp = await this.request("DELETE", url, undefined, options);
    const text = await resp.text();
    if (!text) return {} as unknown as DeleteBaseImageResponse;
    return JSON.parse(text) as DeleteBaseImageResponse;
  }

  /**
   * 
   */
  async commitVm(vm_id: string, body: VmCommitRequest, params?: CommitVmParams, options?: RequestOptions): Promise<VmCommitResponse> {
    let url = `/api/v1/vm/${vm_id}/commit`;
    const searchParams = new URLSearchParams();
    if (params?.keep_paused !== undefined) searchParams.append("keep_paused", String(params.keep_paused));
    if (params?.skip_wait_boot !== undefined) searchParams.append("skip_wait_boot", String(params.skip_wait_boot));
    const qs = searchParams.toString();
    if (qs) url += "?" + qs;
    const resp = await this.request("POST", url, body, options);
    const text = await resp.text();
    if (!text) return {} as unknown as VmCommitResponse;
    return JSON.parse(text) as VmCommitResponse;
  }

  /**
   * 
   */
  async deleteCommit(commit_id: string, options?: RequestOptions): Promise<any> {
    let url = `/api/v1/commits/${commit_id}`;
    const resp = await this.request("DELETE", url, undefined, options);
    const text = await resp.text();
    if (!text) return {};
    return JSON.parse(text);
  }

  /**
   * 
   */
  async updateCommit(commit_id: string, body: UpdateCommitRequest, options?: RequestOptions): Promise<CommitInfo> {
    let url = `/api/v1/commits/${commit_id}`;
    const resp = await this.request("PATCH", url, body, options);
    const text = await resp.text();
    if (!text) return {} as unknown as CommitInfo;
    return JSON.parse(text) as CommitInfo;
  }

  /**
   * 
   */
  async listRepoTags(repo_name: string, options?: RequestOptions): Promise<ListRepoTagsResponse> {
    let url = `/api/v1/repositories/${repo_name}/tags`;
    const resp = await this.request("GET", url, undefined, options);
    const text = await resp.text();
    if (!text) return {} as unknown as ListRepoTagsResponse;
    return JSON.parse(text) as ListRepoTagsResponse;
  }

  /**
   * 
   */
  async createRepoTag(repo_name: string, body: CreateRepoTagRequest, options?: RequestOptions): Promise<CreateRepoTagResponse> {
    let url = `/api/v1/repositories/${repo_name}/tags`;
    const resp = await this.request("POST", url, body, options);
    const text = await resp.text();
    if (!text) return {} as unknown as CreateRepoTagResponse;
    return JSON.parse(text) as CreateRepoTagResponse;
  }

  /**
   * Deploy a GitHub repository to a new Vers project.
   */
  async deployHandler(body: DeployRequest, options?: RequestOptions): Promise<DeployResponse> {
    let url = "/api/v1/deploy";
    const resp = await this.request("POST", url, body, options);
    const text = await resp.text();
    if (!text) return {} as unknown as DeployResponse;
    return JSON.parse(text) as DeployResponse;
  }

  /**
   * 
   */
  async execVm(vm_id: string, body: VmExecRequest, options?: RequestOptions): Promise<VmExecResponse> {
    let url = `/api/v1/vm/${vm_id}/exec`;
    const resp = await this.request("POST", url, body, options);
    const text = await resp.text();
    if (!text) return {} as unknown as VmExecResponse;
    return JSON.parse(text) as VmExecResponse;
  }

  /**
   * 
   */
  async setRepositoryVisibility(repo_name: string, body: SetRepositoryVisibilityRequest, options?: RequestOptions): Promise<any> {
    let url = `/api/v1/repositories/${repo_name}/visibility`;
    const resp = await this.request("PATCH", url, body, options);
    const text = await resp.text();
    if (!text) return {};
    return JSON.parse(text);
  }

  /**
   * 
   */
  async execVmStream(vm_id: string, body: VmExecRequest, options?: RequestOptions): Promise<any> {
    let url = `/api/v1/vm/${vm_id}/exec/stream`;
    const resp = await this.request("POST", url, body, options);
    const text = await resp.text();
    if (!text) return {};
    return JSON.parse(text);
  }

  /**
   * 
   */
  async listDomains(params?: ListDomainsParams, options?: RequestOptions): Promise<DomainResponse[]> {
    let url = "/api/v1/domains";
    const searchParams = new URLSearchParams();
    if (params?.vm_id !== undefined) searchParams.append("vm_id", String(params.vm_id));
    const qs = searchParams.toString();
    if (qs) url += "?" + qs;
    const resp = await this.request("GET", url, undefined, options);
    const text = await resp.text();
    if (!text) return [] as unknown as DomainResponse[];
    return JSON.parse(text) as DomainResponse[];
  }

  /**
   * 
   */
  async createDomain(body: CreateDomainRequest, options?: RequestOptions): Promise<DomainResponse> {
    let url = "/api/v1/domains";
    const resp = await this.request("POST", url, body, options);
    const text = await resp.text();
    if (!text) return {} as unknown as DomainResponse;
    return JSON.parse(text) as DomainResponse;
  }

  /**
   * 
   */
  async sshKey(vm_id: string, options?: RequestOptions): Promise<VmSshKeyResponse> {
    let url = `/api/v1/vm/${vm_id}/ssh_key`;
    const resp = await this.request("GET", url, undefined, options);
    const text = await resp.text();
    if (!text) return {} as unknown as VmSshKeyResponse;
    return JSON.parse(text) as VmSshKeyResponse;
  }

  /**
   * 
   */
  async listImages(options?: RequestOptions): Promise<ListBaseImagesResponse> {
    let url = "/api/v1/images";
    const resp = await this.request("GET", url, undefined, options);
    const text = await resp.text();
    if (!text) return {} as unknown as ListBaseImagesResponse;
    return JSON.parse(text) as ListBaseImagesResponse;
  }

  /**
   * 
   */
  async readFileVm(vm_id: string, params?: ReadFileVmParams, options?: RequestOptions): Promise<VmReadFileResponse> {
    let url = `/api/v1/vm/${vm_id}/files`;
    const searchParams = new URLSearchParams();
    if (params?.path !== undefined) searchParams.append("path", String(params.path));
    const qs = searchParams.toString();
    if (qs) url += "?" + qs;
    const resp = await this.request("GET", url, undefined, options);
    const text = await resp.text();
    if (!text) return {} as unknown as VmReadFileResponse;
    return JSON.parse(text) as VmReadFileResponse;
  }

  /**
   * 
   */
  async writeFileVm(vm_id: string, body: VmWriteFileRequest, options?: RequestOptions): Promise<any> {
    let url = `/api/v1/vm/${vm_id}/files`;
    const resp = await this.request("PUT", url, body, options);
    const text = await resp.text();
    if (!text) return {};
    return JSON.parse(text);
  }

  /**
   * 
   */
  async uploadImage(body: Record<string, unknown>, options?: RequestOptions): Promise<UploadBaseImageResponse> {
    let url = "/api/v1/images/upload";
    const resp = await this.request("POST", url, body, options);
    const text = await resp.text();
    if (!text) return {} as unknown as UploadBaseImageResponse;
    return JSON.parse(text) as UploadBaseImageResponse;
  }

  /**
   * 
   */
  async getPublicRepository(org_name: string, repo_name: string, options?: RequestOptions): Promise<PublicRepositoryInfo> {
    let url = `/api/v1/public/repositories/${org_name}/${repo_name}`;
    const resp = await this.request("GET", url, undefined, options);
    const text = await resp.text();
    if (!text) return {} as unknown as PublicRepositoryInfo;
    return JSON.parse(text) as PublicRepositoryInfo;
  }

  /**
   * 
   */
  async branchByCommit(commit_id: string, body: Record<string, unknown>, params?: BranchByCommitParams, options?: RequestOptions): Promise<NewVmsResponse> {
    let url = `/api/v1/vm/branch/by_commit/${commit_id}`;
    const searchParams = new URLSearchParams();
    if (params?.count !== undefined) searchParams.append("count", String(params.count));
    const qs = searchParams.toString();
    if (qs) url += "?" + qs;
    const resp = await this.request("POST", url, body, options);
    const text = await resp.text();
    if (!text) return {} as unknown as NewVmsResponse;
    return JSON.parse(text) as NewVmsResponse;
  }
}
