// Generated by Sterling SDK Generator
// Orchestrator Control Plane API v0.1.0

/** Response body for GET /env_vars and PUT /env_vars. */
export interface EnvVarsResponse {
  /** All environment variables currently set for the authenticated user. */
  vars: Record<string, unknown>;
}

/** Response body for POST /api/v1/repositories */
export interface CreateRepositoryResponse {
  /** The name of the repository */
  name: string;
  /** The ID of the newly created repository */
  repo_id: string;
}

/** Public repository information (includes owner org name for namespacing) */
export interface PublicRepositoryInfo {
  /** When the repository was created */
  created_at: string;
  /** Optional description */
  description?: unknown;
  /** Full reference: org_name/repo_name */
  full_name: string;
  /** The repository name */
  name: string;
  /** The owning organization's name (namespace) */
  org_name: string;
  /** The repository's unique identifier */
  repo_id: string;
}

/** Response body for GET /api/v1/commit_tags */
export interface ListTagsResponse {
  /** List of all tags in the user's organization */
  tags: TagInfo[];
}

/** Request body for creating a tag within a repository: POST /api/v1/repositories/{repo_name}/tags */
export interface CreateRepoTagRequest {
  /** The commit ID this tag should point to */
  commit_id: string;
  /** Optional description of what this tag represents */
  description?: unknown;
  /** The tag name (e.g. 'latest', 'v1.0') */
  tag_name: string;
}

/** Response struct for GET api/v1/system/version */
export interface OrchestratorVersion {
  /** Executable identifier; should be 'orchestrator' */
  executable_name: string;
  /** Current git hash used for the build */
  git_hash: string;
  /** Current workspace version */
  workspace_version: string;
}

export interface ListCommitsResponse {
  commits: CommitInfo[];
  limit: number;
  offset: number;
  total: number;
}

/** Response body for `POST /api/v1/deploy`. */
export interface DeployResponse {
  project_id: string;
  status: string;
  vm_id: string;
}

/** Response body for GET /api/v1/repositories/{repo_name}/tags */
export interface ListRepoTagsResponse {
  /** The repository name */
  repository: string;
  /** List of tags in this repository */
  tags: RepoTagInfo[];
}

export interface BaseImageInfo {
  base_image_id: string;
  created_at: string;
  description?: unknown;
  image_name: string;
  is_public: boolean;
  owner_id: string;
  size_mib: number;
  source_type: string;
}

/** Response body for POST /api/vm/{vm_id}/exec */
export interface VmExecResponse {
  /** Exec identifier associated with this run. */
  exec_id?: unknown;
  /** Exit code returned by the command. */
  exit_code: number;
  /** UTF-8 decoded stderr (lossy). */
  stderr: string;
  /** UTF-8 decoded stdout (lossy). */
  stdout: string;
}

export interface CreateBaseImageResponse {
  image_name: string;
  job_id: string;
  status: string;
}

/** Request body for POST /api/vm/{vm_id}/exec */
export interface VmExecRequest {
  /** Command and arguments to execute. */
  command: string[];
  /** Optional environment variables to set for the process. */
  env?: unknown;
  /** Optional exec identifier for tracking. */
  exec_id?: unknown;
  /** Optional stdin payload passed to the command. */
  stdin?: unknown;
  /** Timeout in seconds (0 = no timeout). */
  timeout_secs?: unknown;
  /** Optional working directory for the command. */
  working_dir?: unknown;
}

export interface NewVmsResponse {
  vms: NewVmResponse[];
}

/** Request body for POST /api/vm/{vm_id}/exec/stream/attach */
export interface VmExecStreamAttachRequest {
  /** Optional cursor to resume from (exclusive). If omitted, the full retained backlog is replayed. */
  cursor?: unknown;
  /** Identifier of the exec stream session to reattach to. */
  exec_id: string;
  /** Start streaming after the latest retained chunk (ignores cursor). */
  from_latest?: unknown;
}

/** Request body for PATCH /api/vm/{vm_id}/state */
export interface VmUpdateStateRequest {
  /** The requested state for the VM */
  state: VmUpdateStateEnum;
}

export interface DeleteBaseImageResponse {
  base_image_id: string;
  deleted: boolean;
}

/** Response body for GET /api/v1/public/repositories */
export interface ListPublicRepositoriesResponse {
  repositories: PublicRepositoryInfo[];
}

/** Request body for POST /api/v1/commit_tags */
export interface CreateTagRequest {
  /** The commit ID this tag should point to */
  commit_id: string;
  /** Optional description of what this tag represents */
  description?: unknown;
  /** The name of the tag (alphanumeric, hyphens, underscores, dots, 1-64 chars) */
  tag_name: string;
}

/** Response body for GET /api/v1/repositories */
export interface ListRepositoriesResponse {
  /** List of all repositories in the user's organization */
  repositories: RepositoryInfo[];
}

/** Response body for POST /api/v1/repositories/{repo_name}/tags */
export interface CreateRepoTagResponse {
  /** The commit ID this tag points to */
  commit_id: string;
  /** Full reference in image_name:tag format */
  reference: string;
  /** The ID of the newly created tag */
  tag_id: string;
}

export interface CommitInfo {
  commit_id: string;
  created_at: string;
  description?: unknown;
  grandparent_commit_id?: unknown;
  is_public: boolean;
  name: string;
  owner_id: string;
  parent_vm_id?: unknown;
}

/** Response body for DELETE /api/v1/domains/{domain_id} */
export interface DeleteDomainResponse {
  domain_id: string;
}

/** Repository information returned in list and get operations */
export interface RepositoryInfo {
  /** When the repository was created */
  created_at: string;
  /** Optional description */
  description?: unknown;
  /** Whether this repository is publicly visible */
  is_public: boolean;
  /** The repository name */
  name: string;
  /** The repository's unique identifier */
  repo_id: string;
}

/** Response body for POST /api/keys/validate */
export interface ValidateKeyResponse {
  message: string;
  valid: boolean;
}

/** Response body for GET /api/vm/{vm_id}/ssh_key */
export interface VmSshKeyResponse {
  /** The SSH port that will be DNAT'd to the VM's netns (and, in turn, to its TAP device) */
  ssh_port: number;
  /** Private SSH key in stringified OpenSSH format */
  ssh_private_key: string;
}

/** The state of a VM */
export type VmState = "booting" | "running" | "paused" | "sleeping" | "dead";

/** Response body for GET /api/vm/{vm_id}/files */
export interface VmReadFileResponse {
  /** File contents, base64-encoded. */
  content_b64: string;
}

/** Request body for PUT /env_vars — sets (upserts) one or more environment variables.  # Lifecycle model  Environment variables are written to `/etc/environment` inside a VM **once at boot time** via a vsock `WriteFile` request. They are **not** live-synced to running VMs. This is intentional: VMs are ephemeral (create → use → destroy/branch), so env var changes naturally take effect on the next VM.  The `replace` flag exists so callers can atomically express 'I want exactly these variables and nothing else' without having to DELETE each stale key individually. Without it, the only way to remove a variable from future VMs is a separate `DELETE /env_vars/{key}` call per key. */
export interface SetEnvVarsRequest {
  /** If true, delete all existing variables before writing the new set. This gives 'set exactly these vars' semantics. Default: false (upsert). */
  replace?: boolean;
  /** Key-value pairs to set. Keys must be valid shell identifiers (`^[A-Za-z_][A-Za-z0-9_]*$`, max 256 chars). Values max 8192 chars.  When `replace` is false (default): existing keys are overwritten, keys not mentioned are left untouched (upsert semantics).  When `replace` is true: all existing variables are deleted first, then only the provided vars are stored (replace-all semantics). */
  vars: Record<string, unknown>;
}

/** The response body for POST /api/vm/{vm_id}/commit */
export interface VmCommitResponse {
  /** The UUID of the newly-created commit */
  commit_id: string;
}

/** Response body for POST /api/v1/repositories/fork */
export interface ForkRepositoryResponse {
  /** The new commit in your org (snapshot of the forked VM) */
  commit_id: string;
  /** Full reference: repo_name:tag_name */
  reference: string;
  /** The new repository name in your org */
  repo_name: string;
  /** The tag name pointing to the forked commit */
  tag_name: string;
  /** The new VM that was created from the fork */
  vm_id: string;
}

export type ImageSourceRequest =
  | ImageSourceRequest.ImageRef
  | ImageSourceRequest.Bucket
;

export namespace ImageSourceRequest {
  export interface ImageRef {
    image_ref: string;
    type: string;
  }

  export interface Bucket {
    bucket: string;
    key: string;
    type: string;
  }

}

/** Possible options for the state requested in PATCH /api/vm/{vm_id}/state */
export type VmUpdateStateEnum = "Paused" | "Running";

export interface ErrorResponse {
  /** Reason of error */
  error?: string;
  /** Is always: false */
  success?: boolean;
}

/** Request body for PATCH /commits/{commit_id} */
export interface UpdateCommitRequest {
  /** Optional description for the commit. */
  description?: unknown;
  is_public: boolean;
  /** Optional human-readable name for the commit. */
  name?: unknown;
}

/** Request body for POST /api/v1/repositories */
export interface CreateRepositoryRequest {
  /** Optional description of the repository */
  description?: unknown;
  /** The name of the repository (alphanumeric, hyphens, underscores, dots, 1-64 chars) */
  name: string;
}

/** Response type for domain operations. */
export interface DomainResponse {
  created_at: string;
  domain: string;
  domain_id: string;
  vm_id: string;
}

/** The request body for POST /api/vm/{vm_id}/commit */
export interface VmCommitRequest {
  /** If provided, chelsea will use the requested commit UUID. Otherwise, it will generate a UUID itself. */
  commit_id?: unknown;
  /** Optional description for the commit. */
  description?: unknown;
  /** Optional human-readable name for the commit. Defaults to auto-generated name if not provided. */
  name?: unknown;
}

/** Settings for the deploy build pipeline. */
export interface DeploySettings {
  build_command?: unknown;
  install_command?: unknown;
  run_command?: unknown;
  working_directory?: unknown;
}

export interface CreateBaseImageRequest {
  description?: unknown;
  image_name: string;
  /** Additional capacity in MiB beyond the actual filesystem size (defaults to 256). The final image size = calculated rootfs size + this value. Set to 0 for minimum possible image size, or higher for more free space. */
  size_mib?: number;
  source: ImageSourceRequest;
}

/** Request body for POST /api/v1/repositories/fork */
export interface ForkRepositoryRequest {
  /** Name for the new repository in your org (defaults to source_repo if omitted) */
  repo_name?: unknown;
  /** The organization that owns the source public repository */
  source_org: string;
  /** The source repository name */
  source_repo: string;
  /** The tag to fork (e.g. 'latest', 'v1.0') */
  source_tag: string;
  /** Tag name in the new repo (defaults to source_tag if omitted) */
  tag_name?: unknown;
}

export interface VmCommitEntity {
  created_at: string;
  description?: unknown;
  /** The commit that this commit's parent VM was started from, if any. Intended to optimize traversing the commit tree. */
  grandparent_commit_id?: unknown;
  id: string;
  /** Whether this commit is publicly accessible (readable/restorable by anyone). */
  is_public: boolean;
  name: string;
  /** api key id. */
  owner_id: string;
  /** The VM that this commit was created from, if any. */
  parent_vm_id?: unknown;
}

/** Tag information returned in list and get operations */
export interface TagInfo {
  /** The commit ID this tag currently points to */
  commit_id: string;
  /** When the tag was created */
  created_at: string;
  /** Optional description of what this tag represents */
  description?: unknown;
  /** The tag's unique identifier */
  tag_id: string;
  /** The name of the tag */
  tag_name: string;
  /** When the tag was last updated (moved to different commit or description changed) */
  updated_at: string;
}

/** Request body for PUT /api/vm/{vm_id}/files */
export interface VmWriteFileRequest {
  /** File contents, base64-encoded. */
  content_b64: string;
  /** Create parent directories if they don't exist. */
  create_dirs?: boolean;
  /** File mode (e.g. 0644). Defaults to 0644 if omitted. */
  mode?: number;
  /** Destination path on the VM. */
  path: string;
}

/** Streams available for exec logging. */
export type VmExecLogStream = "stdout" | "stderr";

/** Individual log entry describing emitted stdout/stderr chunk. */
export interface VmExecLogEntry {
  /** Base64-encoded bytes from stdout/stderr chunk. */
  data_b64: string;
  exec_id?: unknown;
  stream: VmExecLogStream;
  timestamp: string;
}

export interface LabelVmRequest {
  labels?: unknown;
}

/** Response for GET /api/v1/vm/{vm_id}/metadata */
export interface VmMetadataResponse {
  created_at: string;
  deleted_at?: unknown;
  grandparent_vm_id?: unknown;
  ip: string;
  owner_id: string;
  parent_commit_id?: unknown;
  state: VmState;
  vm_id: string;
}

/** Request body for PATCH /api/v1/repositories/{repo_name}/visibility */
export interface SetRepositoryVisibilityRequest {
  /** Whether the repository should be publicly visible */
  is_public: boolean;
}

/** Request body for PATCH /api/v1/repositories/{repo_name}/tags/{tag_name} */
export interface UpdateRepoTagRequest {
  /** Optional new commit ID to move the tag to */
  commit_id?: unknown;
  /** Optional new description for the tag. Send `null` to clear. */
  description?: unknown;
}

/** Struct representing configuration options common to all VMs */
export interface VmCreateVmConfig {
  /** The disk size, in MiB. */
  fs_size_mib?: unknown;
  /** The filesystem base image name. Currently, must be 'default' */
  image_name?: unknown;
  /** The kernel name. Currently, must be 'default.bin' */
  kernel_name?: unknown;
  labels?: unknown;
  /** The RAM size, in MiB. */
  mem_size_mib?: unknown;
  /** How many vCPUs to allocate to this VM (and its children) */
  vcpu_count?: unknown;
}

/** Response body for new VM requests (new_root, from_commit, branch) */
export interface NewVmResponse {
  vm_id: string;
}

/** Request body for POST /api/v1/vm/from_commit */
export type FromCommitVmRequest =
  | FromCommitVmRequest.CommitId
  | FromCommitVmRequest.TagName
  | FromCommitVmRequest.Ref
;

export namespace FromCommitVmRequest {
  export interface CommitId {
    /** The commit ID to restore from */
    commit_id: string;
  }

  export interface TagName {
    /** The tag name to restore from (legacy org-scoped tag) */
    tag_name: string;
  }

  export interface Ref {
    /** A repository reference in 'repo_name:tag_name' format */
    ref: string;
  }

}

export interface VM {
  created_at: string;
  labels?: unknown;
  owner_id: string;
  state: VmState;
  vm_id: string;
}

/** Request body for POST /api/v1/domains */
export interface CreateDomainRequest {
  domain: string;
  vm_id: string;
}

/** Request body for PATCH /api/v1/commit_tags/{tag_name}  For `description`: - Field absent from JSON → don't change the description - Field present as `null` → clear the description - Field present as `'text'` → set the description to 'text' */
export interface UpdateTagRequest {
  /** Optional new commit ID to move the tag to */
  commit_id?: unknown;
  /** Optional new description for the tag. Send `null` to clear an existing description. */
  description?: unknown;
}

export interface UploadBaseImageResponse {
  image_name: string;
  job_id: string;
  status: string;
}

export interface BaseImageStatusResponse {
  error_message?: unknown;
  image_name: string;
  size_mib: number;
  status: string;
}

export interface ListBaseImagesResponse {
  images: BaseImageInfo[];
  limit: number;
  offset: number;
  total: number;
}

export interface NewRootRequest {
  vm_config: VmCreateVmConfig;
}

/** Request body for PATCH /api/vm/{vm_id}/disk */
export interface VmResizeDiskRequest {
  /** The new disk size in MiB. Must be strictly greater than the current size. */
  fs_size_mib: number;
}

/** Response body for DELETE /api/vm/{vm_id} */
export interface VmDeleteResponse {
  vm_id: string;
}

/** Response body for POST /api/v1/commit_tags */
export interface CreateTagResponse {
  /** The commit ID this tag points to */
  commit_id: string;
  /** The ID of the newly created tag */
  tag_id: string;
  /** The name of the tag */
  tag_name: string;
}

/** Request body for `POST /api/v1/deploy`. */
export interface DeployRequest {
  /** Git branch to clone (defaults to repo default branch). */
  branch?: unknown;
  /** Optional project name (defaults to repo name). */
  name?: unknown;
  /** GitHub repository in `owner/repo` format. */
  repo: string;
  settings?: unknown;
}

/** Tag information within a repository context */
export interface RepoTagInfo {
  /** The commit ID this tag currently points to */
  commit_id: string;
  /** When the tag was created */
  created_at: string;
  /** Optional description */
  description?: unknown;
  /** Full reference in image_name:tag format */
  reference: string;
  /** The tag's unique identifier */
  tag_id: string;
  /** The tag name */
  tag_name: string;
  /** When the tag was last updated */
  updated_at: string;
}

/** Response for exec log tail requests. */
export interface VmExecLogResponse {
  /** Returned log entries. */
  entries: VmExecLogEntry[];
  /** True when the end of file was reached. */
  eof: boolean;
  /** Next byte offset to continue from. */
  next_offset: number;
}


// ── Params types for operations with query parameters ───────────────

export interface ResizeVmDiskParams {
  /** If true, return an error immediately if the VM is still booting. Default: false */
  skip_wait_boot?: boolean;
}

export interface CreateNewRootVmParams {
  /** If true, wait for the newly-created VM to finish booting before returning. Default: false. */
  wait_boot?: boolean;
}

export interface VmLogsParams {
  /** Byte offset into the log file (default: 0) */
  offset?: number;
  /** Maximum number of log entries to return */
  max_entries?: number;
  /** Filter by 'stdout' or 'stderr' */
  stream?: string;
}

export interface BranchByRefParams {
  /** Number of VMs to branch (optional; default 1) */
  count?: number;
}

export interface BranchByTagParams {
  /** Number of VMs to branch (optional; default 1) */
  count?: number;
}

export interface BranchVmParams {
  /** If true, keep VM paused after commit. Only applicable when branching a VM ID. */
  keep_paused?: boolean;
  /** If true, immediately return an error if VM is booting instead of waiting. Only applicable when branching a VM ID. */
  skip_wait_boot?: boolean;
  /** Number of VMs to branch (optional; default 1) */
  count?: number;
}

export interface UpdateVmStateParams {
  /** If true, error immediately if the VM is not finished booting. Defaults to false */
  skip_wait_boot?: boolean;
}

export interface DeleteVmParams {
  /** If true, return an error immediately if the VM is still booting. Default: false */
  skip_wait_boot?: boolean;
}

export interface BranchByVmParams {
  /** If true, keep VM paused after commit */
  keep_paused?: boolean;
  /** If true, immediately return an error if VM is booting instead of waiting */
  skip_wait_boot?: boolean;
  /** Number of VMs to branch (optional; default 1) */
  count?: number;
}

export interface CommitVmParams {
  /** If true, keep VM paused after commit */
  keep_paused?: boolean;
  /** If true, return an error immediately if the VM is still booting. Default: false */
  skip_wait_boot?: boolean;
}

export interface ListDomainsParams {
  /** Filter by VM ID */
  vm_id?: string;
}

export interface ReadFileVmParams {
  /** Absolute path of the file to read */
  path: string;
}

export interface BranchByCommitParams {
  /** Number of VMs to branch (optional; default 1) */
  count?: number;
}

